---
- name: Install Development packages
  hosts: development
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: "Install packages"
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - build-essential
          - crossbuild-essential-amd64
          - crossbuild-essential-arm64
          - crossbuild-essential-armhf
          - git
          - golang
          - nodejs
          - make
          - jq
          - sed
