---
- name: Install Development packages
  hosts: development
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  # pre_tasks:
  #   - name: 'Install python'
  #     raw: sudo apt-get -y install python python-apt

  tasks:
    - name: Update packager cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes

    - name: "Install packages"
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - build-essential
          - crossbuild-essential-amd64
          - crossbuild-essential-arm64
          - crossbuild-essential-armhf
          - git
          - golang
          - nodejs
          - make
          - jq
          - sed