---
- name: Jellyfin via Podman
  hosts: nas
  become: yes
  become_user: root
  become_method: sudo

  handlers:
    - name: Restart nginx
      service: name=nginx state=restarted
      when: '"nginx" in services'

  tasks:
    - name: Install Podman
      package:
        name: podman
        state: present

    - name: Create Jellyfin Pod
      shell: |
        podman run \
          --pod=new:jellyfin -dt \
          --label "io.containers.autoupdate=registry" \
          --publish 8096:8096/tcp \
          --volume /main/system/jellyfin/cache:/cache:Z \
          --volume /main/system/jellyfin/config:/config:Z \
          --mount type=bind,source=/main/multimedia,destination=/media,ro=true \
          docker.io/jellyfin/jellyfin:latest
      ignore_errors: yes

    - name: Create SystemD service for jellyfin Pods
      shell: |
        podman generate systemd --files --name jellyfin
      args:
        chdir: /etc/systemd/system/

    - name: Set nginx config for jellyfin
      blockinfile:
        create: yes
        path: /etc/nginx/sites-enabled/jellyfin
        block: |
          server {
            listen 443 ssl;
            server_name media.setale.me;

            ssl_certificate      /etc/ssl/setale.me/cert.crt;
            ssl_certificate_key  /etc/ssl/setale.me/cert-priv.pem;
            ssl_protocols       TLSv1.2 TLSv1.3;

            ssl_ciphers                 ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256;
            ssl_prefer_server_ciphers   on;
            ssl_ecdh_curve              secp384r1;

            location / {
              proxy_read_timeout 300;
              proxy_pass http://localhost:8096;
            }
          }
      notify: Restart nginx
      when: '"nginx" in services'

    - name: Enable jellyfin systemd service
      service:
        name: pod-jellyfin
        enabled: yes
        state: started

    - name: Stop at midnight jellyfin
      cron:
        user: root
        name: stop at midnight jellyfin
        minute: "40"
        hour: "23"
        job: service pod-jellyfin stop

    - name: Start at 6:30 daily
      cron:
        user: root
        name: start at 6:30 jellyfin
        minute: "30"
        hour: "7"
        job: service pod-jellyfin start