---
# See https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/index.html
- name: Setup OpenZFS devices
  hosts: nas
  become: yes
  become_user: root
  become_method: sudo

  vars_prompt:
    - name: zfs_personal_pwd
      prompt: "Enter OpenZFS Encryption key for Personal volume"
      private: yes
    - name: zfs_backups_pwd
      prompt: "Enter OpenZFS Encryption key for Backups volume"
      private: yes

  tasks:
    # - name: Fail on Kernels not 5.10
    #   fail:
    #     msg: OpenZFS supports only Raspberry Pi Kernel 5.10 (Current {{ ansible_kernel }})
    #   when: ansible_kernel |  version('5.10','>')

    - name: "Install dependencies"
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          # - raspberrypi-kernel-headers
          - dpkg-dev
          # Dependencies for rpi-source and rpi-update
          - git
          - bc
          - bison
          - flex
          - libssl-dev
          - libncurses5-dev
          - rpi-update
      when: ansible_os_family == "Debian"

    - name: Install 5.10 kernel
      shell: BRANCH=oldstable rpi-update

    - reboot:
        reboot_timeout: 300
        post_reboot_delay: 15
        pre_reboot_delay: 15

    - name: Install/Update rpi-source
      get_url:
        url: "https://raw.githubusercontent.com/RPi-Distro/rpi-source/master/rpi-source"
        dest: "/usr/local/bin/rpi-source"
        mode: 0755

    - shell: /usr/local/bin/rpi-source -q --tag-update

    - name: Download kernel headers
      shell: /usr/local/bin/rpi-source

    - name: Add Debian Backports
      apt_repository:
        repo: "deb http://deb.debian.org/debian bullseye-backports main contrib"
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Debian Backports (src)
      apt_repository:
        repo: "deb-src http://deb.debian.org/debian bullseye-backports main contrib"
        state: present
      when: ansible_os_family == "Debian"

    - name: Adds APT Preferences for OpenZFS Backports
      blockinfile:
        path: /etc/apt/preferences.d/90_zfs
        create: yes
        block: |
          Package: src:zfsutils-linux
          Pin: release n=bullseye-backports
          Pin-Priority: 990
      when: ansible_os_family == "Debian"

    - name: Update APT cache with the new rules
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install packages"
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - zfsutils-linux
          - zfs-dkms
          - zfs-auto-snapshot

    - name: Makes sure that encryption keys are stored safe in path
      file:
        state: directory
        path: "/boot/values"
        owner: root
        group: root
        mode: "0655"

    - name: Adds encryption keys ({{ item.name }})
      copy:
        dest: item.path
        content: item.pwd
        owner: root
        group: root
        mode: "0600"
      loop:
        - { name: "OpenZFS - NAS - Personal", path: "/boot/values/personal", pwd: "{{ zfs_personal_pwd }} "}
        - { name: "OpenZFS - NAS - Backup", path: "/boot/values/backups", pwd: "{{ zfs_backups_pwd }}"}

    - name: modprobe zfs
      modprobe:
        name: zfs
        state: present

    - shell: zfs load-key -a
    - shell: zfs mount -a

    - name: Load Keys at Reboot
      cron:
        name: "Load keys and mount at reboot"
        user: root
        special_time: reboot
        job: "sleep 5; /usr/sbin/zpool import -d /dev/ -a; /usr/sbin/zfs load-key -a ; /usr/sbin/zfs mount -a"

    - name: Add cronjob to Scrub Monthly
      cron:
        name: "Scrub disk once a month"
        user: root
        special_time: monthly
        job: "/usr/sbin/zpool scrub main"
