---
- name: Setup OpenZFS devices
  hosts: nas
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: "Install packages for RaspberryPi"
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - raspberrypi-kernel-headers
          - dpkg-dev
      when: ansible_os_family == "Debian"

    - name: Add Debian Backports
      apt_repository:
        repo: "deb http://deb.debian.org/debian buster-backports main contrib"
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Debian Backports (src)
      apt_repository:
        repo: "deb-src http://deb.debian.org/debian buster-backports main contrib"
        state: present
      when: ansible_os_family == "Debian"

    - name: Adds APT Preferences for OpenZFS Backports
      blockinfile:
        path: /etc/apt/preferences.d/90_zfs
        block: |
          Package: libnvpair1linux libnvpair3linux libuutil1linux libuutil3linux libzfs2linux libzfs4linux libzpool2linux libzpool4linux spl-dkms zfs-dkms zfs-test zfsutils-linux zfsutils-linux-dev zfs-zed
          Pin: release n=buster-backports
          Pin-Priority: 990
      when: ansible_os_family == "Debian"

    - name: Update APT cache with the new rules
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install packages"
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - zfsutils-linux
          - zfs-dkms
          - zfs-auto-snapshot

    - name: Makes sure that encryption keys are stored safe in path
      file:
        state: directory
        path: "/boot/values"
        owner: root
        group: root
        mode: "0655"

    - name: Adds encryption keys ({{ item.name }})
      copy:
        dest: item.path
        content: "{{ lookup('community.general.onepassword', item.name, field='password') }}"
        owner: root
        group: root
        mode: "0600"
      loop:
        - { name: "OpenZFS - NAS - Personal", path: "/boot/values/personal"}
        - { name: "OpenZFS - NAS - Backup", path: "/boot/values/backups"}

    - name: modprobe zfs
      modprobe:
        name: zfs
        state: present

    - shell: zfs load-key -a
    - shell: zfs mount -a

    - name: Load Keys at Reboot
      cron:
        name: "Load keys and mount at reboot"
        user: root
        special_time: reboot
        job: "sleep 5 ; /usr/sbin/zfs load-key -a ; /usr/sbin/zfs mount -a"

    - name: Add cronjob to Scrub Monthly
      cron:
        name: "Scrub disk once a month"
        user: root
        special_time: monthly
        job: "/usr/sbin/zpool scrub main"
