---
- name: Setup OpenZFS devices
  hosts: nas
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: "Install packages"
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: present
      vars:
        packages:
          - zfsutils-linux
          - zfs-initramfs
          - zfs-dkms

    - name: Adds encryption keys (personal)
      copy:
        dest: "/boot/values/personal"
        content: "{{ lookup('community.general.onepassword', 'OpenZFS - NAS - Personal', field='password') }}"
        owner: root
        group: root
        mode: "0600"

    - name: Adds encryption keys (backups)
      copy:
        dest: "/boot/values/backups"
        content: "{{ lookup('community.general.onepassword', 'OpenZFS - NAS - Backup', field='password') }}"
        owner: root
        group: root
        mode: "0600"

    - shell: zfs load-key -a
    - shell: zfs mount -a

    - name: Load Keys at Reboot
      cron:
        name: "Load keys and mount at reboot"
        user: root
        special_time: reboot
        job: "sleep 5 ; /usr/sbin/zfs load-key -a ; /usr/sbin/zfs mount -a"

    - name: Scrub Monthly
      cron:
        name: "Scrub disk once a month"
        user: root
        special_time: monthly
        job: "/usr/sbin/zpool scrub main"
