---
- name: Setup OpenZFS devices
  hosts: nas
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Update packager cache
      apt:
        update_cache: yes

    - name: "Install packages"
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - zfsutils-linux
          - zfs-initramfs
          - cryptsetup
          - mdadm

    - name: Disable SWAP 
      shell: |
        swapoff -a