---
- name: Install NAS packages
  hosts: nas
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Update packager cache
      apt:
        update_cache: yes

    - name: "Install packages"
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - unattended-upgrades
          - moreutils
          - jq
          - sed
          - gpg
          - make
          - git
