---
- name: Transmission BitTorrent
  hosts: nas
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  handlers:
    - name: Restart nginx
      service: name=nginx state=restarted

  tasks:
    - package:
        name: "transmission-daemon"
        state: present

    - service:
        name: transmission-daemon
        state: stopped

    - name: Create partials downloads directory
      file:
        state: directory
        path: "/main/downloads/.partials"
        owner: root
        group: root
        mode: "0777"

    - name: Set nginx config for transmission
      blockinfile:
        create: yes
        path: /etc/nginx/sites-enabled/transmission
        block: |
          server {
            listen 443 ssl;
            server_name dwn.setale.me bt.setale.me;

            ssl_certificate      /etc/ssl/setale.me/cert.crt;
            ssl_certificate_key  /etc/ssl/setale.me/cert-priv.pem;
            ssl_protocols       TLSv1.2 TLSv1.3;

            ssl_ciphers                 ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256;
            ssl_prefer_server_ciphers   on;
            ssl_ecdh_curve              secp384r1;

            location / {
              proxy_pass http://localhost:19091;
            }
          }
      notify: Restart nginx

    - name: "Copy the config"
      copy:
        remote_src: false
        src: "transmission.json"
        dest: /etc/transmission-daemon/settings.json
        owner: debian-transmission
        group: debian-transmission
        mode: 0600

    - name: Start Transimission systemd service
      service:
        name: transmission-daemon
        state: restarted
        enabled: yes

