---
- name: Sets user access
  hosts: nas
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted

  tasks:
    - name: Authorize my keys (GitLab)
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: https://gitlab.com/koalalorenzo.keys

    - name: Authorize my keys (GitHub)
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: https://github.com/koalalorenzo.keys

    - name: Uses Bash shell
      cron:
        user: "{{ ansible_user }}"
        name: SHELL
        env: yes
        job: /bin/bash

    - name: Adds GPG Key
      cron:
        user: "{{ ansible_user }}"
        name: GPG_CMD
        env: yes
        job: ifne /usr/bin/gpg --batch --armor --trust-model always --no-default-keyring --keyring /main/system/email.asc.gpg --recipient lorenzo@setale.me --encrypt

    - name: Adds Email notification
      cron:
        user: "{{ ansible_user }}"
        name: MAILTO
        env: yes
        job: lorenzo@setale.me

    - name: Secure SSH by Allowing current user
      lineinfile:
        path: /etc/ssh/sshd_config
        line: AllowUsers {{ ansible_user }}
        state: present
        mode: 0644
      notify: Restart ssh

    - name: Secure SSH by denying Pi
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'DenyUsers pi'
        state: present
        mode: 0644
      notify: Restart ssh
