---
- import_playbook: common.yaml
- import_playbook: nas.yaml

# Home Automation
- import: homeauto/hue_exporter.yaml

# Final Setup and reboot
- import_playbook: common/overlay-on.yaml
- import_playbook: common/reboot.yaml
