---
- import_playbook: common/upgrade.yaml
- import_playbook: common/locale.yaml
- import_playbook: common/hostname.yaml
- import_playbook: common/ssh-secure.yaml
- import_playbook: common/reboot.yaml
# Post reboot setup
- import_playbook: common/certificates.yaml
- import_playbook: common/firewall.yaml
- import_playbook: common/cleanup.yaml

# Development tools
- import_playbook: development/tools.yaml
# - import_playbook: development/golang.yaml
# - import_playbook: development/docker.yaml
# - import_playbook: development/nomad.yaml

# Pihole stuff
- import_playbook: pihole/unbound.yaml
- import_playbook: pihole/firewall.yaml
- import_playbook: pihole/upgrade.yaml
- import_playbook: pihole/gravity-update.yaml

# Final Reboot
- import_playbook: common/reboot.yaml
