---
- import_playbook: common/packages.yaml
- import_playbook: common/config.yaml
# - import_playbook: common/hostname.yaml
- import_playbook: common/firewall.yaml
- import_playbook: common/ssh-secure.yaml
- import_playbook: common/reboot.yaml
# # Post reboot setup
- import_playbook: common/tailscale.yaml
- import_playbook: common/antivirus.yaml

# Development tools
- import_playbook: development/packages.yaml
# - import_playbook: development/golang.yaml
# - import_playbook: development/docker.yaml
# - import_playbook: development/nomad.yaml

# NAS
- import_playbook: nas/swap.yaml
- import_playbook: nas/users.yaml
- import_playbook: nas/nginx.yaml
- import_playbook: nas/zram.yaml
- import_playbook: nas/openzfs.yaml
- import_playbook: nas/email.yaml
- import_playbook: nas/monitoring.yaml
- import_playbook: nas/packages.yaml
- import_playbook: common/reboot.yaml
- import_playbook: nas/samba.yaml
- import_playbook: nas/restic.yaml
- import_playbook: nas/gickup.yaml

# Pihole stuff
- import_playbook: pihole/unbound.yaml
- import_playbook: pihole/firewall.yaml
- import_playbook: pihole/upgrade.yaml
- import_playbook: pihole/gravity-update.yaml

# Final Reboot
- import_playbook: common/reboot.yaml
