---
- import_playbook: common/packages.yaml
- import_playbook: common/config.yaml
# - import_playbook: common/hostname.yaml
- import_playbook: common/ssh-secure.yaml
- import_playbook: common/reboot.yaml
# # Post reboot setup
- import_playbook: common/firewall.yaml
- import_playbook: common/tailscale.yaml
- import_playbook: common/antivirus.yaml
- import_playbook: common/cleanup.yaml

# Development tools
- import_playbook: development/packages.yaml
# - import_playbook: development/golang.yaml
# - import_playbook: development/docker.yaml
# - import_playbook: development/nomad.yaml

# NAS
- import_playbook: nas/openzfs.yaml
- import_playbook: nas/email.yaml
- import_playbook: nas/packages.yaml
- import_playbook: nas/users.yaml
- import_playbook: nas/samba.yaml
- import_playbook: nas/restic.yaml

# Pihole stuff
- import_playbook: pihole/unbound.yaml
- import_playbook: pihole/firewall.yaml
- import_playbook: pihole/upgrade.yaml
- import_playbook: pihole/gravity-update.yaml

# Work VM / Station
- import_playbook: work/amazon-ssm.yaml
- import_playbook: work/qualys.yaml
- import_playbook: work/anyconnect.yaml

# Final Reboot
- import_playbook: common/reboot.yaml
