---
- import_playbook: common.yaml

# # # NAS
- import_playbook: nas/openzfs.yaml
- import_playbook: nas/email.yaml
# # - import_playbook: nas/zram.yaml
- import_playbook: nas/packages.yaml
# - import_playbook: nas/samba.yaml
- import_playbook: nas/restic.yaml
# - import_playbook: nas/gickup.yaml

# # Pihole stuff
- import_playbook: pihole/unbound.yaml
- import_playbook: pihole/firewall.yaml
- import_playbook: pihole/pihole-setup.yaml
# - import_playbook: pihole/upgrade.yaml
# - import_playbook: pihole/gravity-update.yaml

# Home Automation
- import: homeauto/hue_exporter.yaml

# Final Setup and reboot
- import_playbook: common/overlay-on.yaml
- import_playbook: common/reboot.yaml
