---
- name: Setup Docker for Nomad Clients
  hosts: nomadClients
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  handlers:
    - name: Restart Nomad
      service: name=nomad state=restarted
    - name: Restart Docker
      service: name=docker state=restarted

  tasks:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: "Install install Docker"
      package:
        name: docker-ce
        update_cache: yes
        state: latest

    - copy:
        dest: "/etc/docker/daemon.json"
        content: ""
      notify: Restart Docker

    - blockinfile:
        path: /etc/nomad.d/client.hcl
        marker: "# {mark} ANSIBLE MANAGED Docker"
        block: |
          plugin "docker" {
            config {
              allow_privileged = true

              gc {
                image       = true
                image_delay = "72h"
                container   = true
              }
            }
          }
      notify: Restart Nomad
