---
- name: Setup Nomad Client
  hosts: nomadClients
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  handlers:
    - name: Restart Nomad
      service: name=nomad state=restarted

  tasks:
    - file:
        path: "{{ item.path }}"
        state: directory
      loop: "{{ host_volumes }}"

    - ufw:
        proto: "{{ item.proto }}"
        port: "{{ item.port }}"
        rule: allow
      loop:
        - { proto: any, port: 53 } # DNS / PiHole, AdGuard or Unbound
        - { proto: any, port: 80 } # HTTP
        - { proto: any, port: 443 } # HTTPS
        - { proto: any, port: 853 } # DNS over TLS / QUIC
        - { proto: any, port: 8081 } # Traefik
        - { proto: any, port: 1900 } # Jellyfin DLNA / upnp
        - { proto: any, port: 7359 } # Jellyfin autodiscovery
        - { proto: any, port: 7777 } # Terraria
        - { proto: any, port: 5201 } # Iperf 3

    - ufw:
        rule: allow
        proto: tcp
        port: "20000:32000"

    - ufw:
        rule: allow
        proto: udp
        port: "20000:32000"

    - service:
        name: consul
        enabled: true
        state: started
      ignore_errors: true

    - service:
        name: nomad
        enabled: true
        state: started
      ignore_errors: true
