---
- name: Setup Nomad Client
  hosts: nomadClients
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  handlers:
    - name: Restart Nomad
      service: name=nomad state=restarted

  tasks:
    - blockinfile:
        path: /etc/nomad.d/client.hcl
        create: yes
        mode: 0700
        block: |
          client {
            enabled = true
            servers = [{% for i in groups['nomadServers'] %}"{{ i }}:4647",{% endfor %}]

            options = {
              "driver.denylist" = "java"
            }
          }

          plugin "raw_exec" {
            config {
              enabled = true
            }
          }
      notify: Restart Nomad
