---
- name: Common setup for Nomad machines
  hosts: nomad
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: "Install dependencies packages"
      package:
        name:
          - wget
          - gpg
          - coreutils
          - openssl
          - software-properties-common
          - ca-certificates
          - apt-transport-https
        update_cache: yes
        state: present

    - name: Add Hashicorp GPG Key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /usr/share/keyrings/hashicorp-archive-keyring.asc

    - name: adds Hashicorp Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: "Install install Nomad Packages"
      package:
        name:
          - nomad
          - docker-ce
        update_cache: yes
        state: latest
