---
- name: Install Consul on all the machines
  hosts: consul
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  handlers:
    - name: restart consul
      service: name=consul state=restarted
      ignore_errors: true

    - name: reload consul
      command: consul reload
      ignore_errors: true

  tasks:
    - name: Load encrypted credentials
      community.sops.load_vars:
        file: consul.sops.yaml

    - file:
        path: /etc/consul.d
        state: directory
        owner: consul
        group: consul
        mode: "0700"

    - file:
        path: /etc/consul.d/certs
        state: directory
        owner: consul
        group: consul
        mode: "0700"

    - name: Upload certificates
      no_log: true
      copy:
        mode: 0700
        owner: consul
        group: consul
        dest: "/etc/consul.d/certs/{{ item.key }}"
        content: "{{ item.value }}"
      with_dict: "{{ consul_certs }}"
      notify: reload consul

    - copy:
        dest: /etc/consul.d/consul.hcl
        mode: 0700
        owner: consul
        group: consul
        content: |
          data_dir = "/opt/consul"
          datacenter = "dc1"
          encrypt = "{{ consul_gossip_key }}"
          server = true
          bootstrap_expect = {{ bootstrap_quorum }}
          bind_addr = "0.0.0.0"
          advertise_addr = "{{ ansible_all_ipv4_addresses | ansible.utils.ipaddr('100.64.0.0/10') | first }}"

          ui_config {
            enabled = true
          }

          telemetry { 
            prometheus_retention_time = "90s"
          }

          retry_join = [{% for i in groups['nomadServers'] %}"{{ i }}.{{ tailscale_domain }}",{% endfor %}]

          tls {
             defaults {
                ca_file = "/etc/consul.d/certs/consul-agent-ca.pem"
                cert_file = "/etc/consul.d/certs/dc1-server-consul-0.pem"
                key_file = "/etc/consul.d/certs/dc1-server-consul-0-key.pem"

                verify_incoming = true
                verify_outgoing = true
             }
             internal_rpc {
                verify_server_hostname = true
             }
          }

          acl = {
            enabled = false
            default_policy = "allow"
            enable_token_persistence = true
          }

          auto_encrypt {
            allow_tls = true
          }
      notify: restart consul

    - name: Re-joins after reboot
      cron:
        name: "rejoin consul cluster after reboot"
        user: root
        special_time: reboot
        job: "retry -t 10 -- consul join {% for i in groups['nomadServers'] %}{{ i }} {% endfor %}"
