---
- name: Reset Nomad raft
  hosts: nomadClients
  serial: 1
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - service:
        name: nomad
        state: stopped

    - pause:
        seconds: 15

    - file:
        path: "/opt/nomad/data/server/raft"
        state: absent

    - service:
        name: nomad
        state: restarted
