---
- name: Setup Nomad Servers (systemd)
  hosts: nomadServers
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  handlers:
    - name: Restart Nomad
      service: name=nomad state=restarted

  tasks:
    - name: Adds Nomad Server configuration
      blockinfile:
        path: /etc/nomad.d/server.hcl
        create: yes
        mode: 0700
        block: |
          server {
            enabled = true
            bootstrap_expect = {{ bootstrap_expected }}

            server_join {
              retry_join = [ {% for i in groups['nomadServers'] %}"{{ i }}:4647",{% endfor %} ]
              retry_interval = "5s"
            }
          }
      notify: Restart Nomad
