---
- name: PiHole config for manual setup
  hosts: dns
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  handlers:
    - name: Restart nginx
      service: name=nginx state=restarted

  vars_prompt:
    - name: web_password
      prompt: "Enter the password for PiHole Service"
      private: yes

  tasks:
    - name: Setup config directory
      file:
        state: directory
        path: "/etc/pihole"
        owner: root
        group: root
        mode: "0655"

    - name: Populate /etc/pihole/setupVars.conf
      template:
        src: setupVars.conf.tmpl
        dest: /etc/pihole/setupVars.conf
        mode: "0755"
      register: setupvar

    - name: Reload config if settings changesd
      when: setupvar.changed
      shell: pihole -r

    - name: "Ensures UFW is available"
      package:
        name: ufw
        state: present

    - name: Configure DNS on UFW (UDP)
      ufw:
        rule: allow
        port: 53
        proto: udp

    - name: Configure DNS on UFW (tcp)
      ufw:
        rule: allow
        port: 53
        proto: tcp
