---
- name: Setup Cisco VPN (Anyconnect)
  hosts: visma
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Create temp directory
      tempfile:
        state: directory
        suffix: ansible-anyconnect
      register: temp
    - name: Create temp directory for decompressing-files
      tempfile:
        state: directory
        suffix: ansible-anyconnect-files
      register: tempfiles

    - copy:
        src: ./files/anyconnect-linux64-4.9.06037-predeploy-k9.tar.gz
        dest: "{{ temp.path }}/"
    
    - unarchive:
        src: "{{ temp.path }}/anyconnect-linux64-4.9.06037-predeploy-k9.tar.gz"
        dest: "{{ tempfiles.path }}/"

    # Deleting the license.txt does not trigger input to accept it
    - file:
        path: "{{ tempfiles.path }}/vpn/license.txt"
        state: absent