---
# See https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/index.html
- name: Setup OpenZFS devices
  hosts: storage
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Load encrypted credentials
      community.sops.load_vars:
        file: openzfs.sops.yaml

    - when: ansible_distribution == 'Debian'
      block:
        - name: "Install dependencies"
          package:
            state: present
            name:
              # - raspberrypi-kernel-headers
              - dpkg-dev
              # Dependencies for rpi-source and rpi-update
              - git
              - bc
              - bison
              - flex
              - libssl-dev
              - libncurses5-dev
              - rpi-update

        - name: Install 5.10 kernel
          shell: BRANCH=oldstable rpi-update

        - reboot:
            reboot_timeout: 300
            post_reboot_delay: 15
            pre_reboot_delay: 15

        - name: Install/Update rpi-source
          get_url:
            url: "https://raw.githubusercontent.com/RPi-Distro/rpi-source/master/rpi-source"
            dest: "/usr/local/bin/rpi-source"
            mode: 0755

        - shell: /usr/local/bin/rpi-source -q --tag-update

        - name: Download kernel headers
          shell: /usr/local/bin/rpi-source
          ignore_errors: yes

        - name: Add Debian Backports
          apt_repository:
            repo: "deb http://deb.debian.org/debian bullseye-backports main contrib"
            state: present

        - name: Add Debian Backports (src)
          apt_repository:
            repo: "deb-src http://deb.debian.org/debian bullseye-backports main contrib"
            state: present

        - name: Adds APT Preferences for OpenZFS Backports
          blockinfile:
            path: /etc/apt/preferences.d/90_zfs
            create: yes
            block: |
              Package: libnvpair1linux libnvpair3linux libuutil1linux libuutil3linux libzfs2linux libzfs4linux libzpool2linux libzpool4linux spl-dkms zfs-dkms zfs-test zfsutils-linux zfsutils-linux-dev zfs-zed
              Pin: release n=bullseye-backports
              Pin-Priority: 990

        - name: Update APT cache with the new rules
          apt:
            update_cache: yes

    - name: "Install packages (may take a while)"
      package:
        state: latest
        name:
          - zfsutils-linux
          - zfs-dkms
          - zfs-auto-snapshot
          - nfs-kernel-server
          - nfs-common

    - name: Makes sure that encryption keys are stored safe in path
      file:
        state: directory
        path: "/etc/zfskeys/"
        owner: root
        group: root
        mode: "0755"

    - name: Adds encryption keys
      copy:
        dest: "{{ item.path }}"
        content: "{{ item.pwd }}"
        owner: root
        group: root
        mode: "0600"
      loop:
        - { path: "/etc/zfskeys/personal", pwd: "{{ zfs_personal_pwd }}" }
        - { path: "/etc/zfskeys/backups", pwd: "{{ zfs_backups_pwd }}" }

    - name: modprobe zfs
      modprobe:
        name: zfs
        state: present

    - name: "Reduce RAM usage to 1/3 of memory"
      sysctl:
        name: vfs.zfs.arc_max
        value: "{{(ansible_memtotal_mb / 3) | int}}m"
      ignore_errors: true

    - shell: zfs load-key -a
    - shell: zfs mount -a

    - name: Load Keys at Reboot
      cron:
        name: "Load keys and mount at reboot"
        user: root
        special_time: reboot
        job: "sleep 5; /usr/sbin/zpool import -d /dev/ -a; /usr/sbin/zfs load-key -a ; /usr/sbin/zfs mount -a"

    - name: Add cronjob to Scrub disks
      cron:
        name: "Scrub disk once a every 2 weeks"
        user: root
        hour: "2"
        minute: "30"
        day: "2, 16"
        job: "/usr/sbin/zpool scrub main"

    - ufw:
        proto: "any"
        port: "nfs"
        src: "{{ item }}"
        rule: allow
      loop:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
