---
- name: Ensures Certificates are trusted
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Check if /usr/share/ca-certificates exists
      stat:
        path: /usr/share/ca-certificates
      register: share_ca_crt

    - name: Ensure qm64 CA directory exists (/usr/share/ca-certificates)
      file:
        path: /usr/share/ca-certificates/qm64
        mode: 0755
        owner: root
        group: root
        state: directory
      when: share_ca_crt.stat.exists and share_ca_crt.stat.isdir

    - name: Copy latest Vault CA cert
      get_url:
        url: https://vault.qm64.tech/v1/pki/ca/pem
        dest: /usr/share/ca-certificates/qm64/vault.crt
        mode: 0644
      when: share_ca_crt.stat.exists and share_ca_crt.stat.isdir
      ignore_errors: true

    - name: Copy latest Vault CA Fullchain
      get_url:
        url: https://vault.qm64.tech/v1/pki/ca_chain
        dest: /usr/share/ca-certificates/qm64/vault-chain.crt
        mode: 0644
      ignore_errors: true
      when: share_ca_crt.stat.exists and share_ca_crt.stat.isdir

    - name: Check if /etc/ssl/certs exists
      stat:
        path: /etc/ssl/certs
      register: etc_ssl_certs

    - name: Copy latest Vault CA cert
      get_url:
        url: https://vault.qm64.tech/v1/pki/ca/pem
        dest: /etc/ssl/certs/qm64-vault.crt
        mode: 0644
      when: etc_ssl_certs.stat.exists and etc_ssl_certs.stat.isdir
      ignore_errors: true

    - name: Copy latest Vault CA Fullchain
      get_url:
        url: https://vault.qm64.tech/v1/pki/ca_chain
        dest: /etc/ssl/certs/qm64-vault-chain.crt
        mode: 0644
      ignore_errors: true
      when: etc_ssl_certs.stat.exists and etc_ssl_certs.stat.isdir

    - name: Update CA
      shell: update-ca-certificates -f