---
- name: Bunch of generic configuration
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Ensure the locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present

    - name: set as default locale
      command: localectl set-locale LANG=en_US.UTF-8

    - name: Uses bash shell in cron
      cron:
        name: SHELL
        user: root
        env: yes
        job: /bin/bash

    - name: Set timezone to UTC
      timezone:
        name: Etc/UTC
