---
- name: Sets DNS records for hostname
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: Load encrypted credentials (SSL)
      community.sops.load_vars:
        file: cloudflare.sops.yaml

    - name: Create cloudflare CNAME records to tailscale
      cloudflare_dns:
        api_token: "{{ cloudflare_api_token }}"
        account_email: "{{ cloudflare_email }}"
        zone: "{{ main_domain }}"
        record: "{{ ansible_host }}.{{ tailscale_domain }}"

        type: CNAME
        value: "{{ ansible_host }}.{{ main_domain }}"
        ttl: 60
        state: present
