---
- name: Updates the locale used (to use mosh)
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Ensure the locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present

    - name: set as default locale
      command: localectl set-locale LANG=en_US.UTF-8