---
- name: Setup Grafana Agent
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  handlers:
    - name: Restart grafana-agent
      service: name=grafana-agent state=restarted

  tasks:
    - name: Load encrypted credentials
      community.sops.load_vars:
        file: monitoring_grafana.sops.yaml

    - apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - package:
        name: grafana-agent
        state: latest
      notify: Restart grafana-agent

    - name: Add Grafana config file
      copy:
        dest: /etc/grafana-agent.yaml
        mode: 0644
        content: |
          integrations:
            cadvisor:
              enabled: true
              docker_only: true
              instance: {{ ansible_hostname }}
              relabel_configs:
              - action: replace
                replacement: integrations/docker
                target_label: job
              metric_relabel_configs:
              - action: keep
                regex: container_cpu_usage_seconds_total|container_fs_inodes_free|container_fs_inodes_total|container_fs_limit_bytes|container_fs_usage_bytes|container_last_seen|container_memory_usage_bytes|container_network_receive_bytes_total|container_network_tcp_usage_total|container_network_transmit_bytes_total|container_spec_memory_reservation_limit_bytes|machine_memory_bytes|machine_scrape_error
                source_labels:
                - __name__
            prometheus_remote_write:
            - basic_auth:
                password: {{ grafana_token }}
                username: {{ grafana_prometheus_username }}
              url: {{ grafana_prometheus_url }}
            agent:
              enabled: true
              relabel_configs:
              - action: replace
                source_labels:
                - agent_hostname
                target_label: instance
              - action: replace
                target_label: job
                replacement: "integrations/agent-check"
              metric_relabel_configs:
              - action: keep
                regex: (prometheus_target_.*|prometheus_sd_discovered_targets|agent_build.*|agent_wal_samples_appended_total|process_start_time_seconds)
                source_labels:
                - __name__
            consul_exporter:
              enabled: true
              relabel_configs:
                - replacement: {{ ansible_hostname }}
                  target_label: instance
            # Add here any snippet that belongs to the `integrations` section.
            # For a correct indentation, paste snippets copied from Grafana Cloud at the beginning of the line.
            node_exporter:
              enabled: true
              # disable unused collectors
              disable_collectors:
                - ipvs #high cardinality on kubelet
                - btrfs
                - infiniband
                - xfs
                - nfs
              enable_collectors:
                - meminfo_numa
                - processes
                - systemd
                - zfs
              # exclude dynamic interfaces
              netclass_ignored_devices: "^(veth.*|cali.*|[a-f0-9]{15})$"
              netdev_device_exclude: "^(veth.*|cali.*|[a-f0-9]{15})$"
              # disable tmpfs
              filesystem_fs_types_exclude: "^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|tmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$"
              # drop extensive scrape statistics
              metric_relabel_configs:
              - action: drop
                regex: (node_scrape_collector_.*|node_nfsd_.*|node_systemd_socket_.*)
                source_labels: [__name__]
              relabel_configs:
              - replacement: {{ ansible_hostname }}
                target_label: instance
          ###
          logs:
            configs:
            - clients:
              - basic_auth:
                  password: {{ grafana_token }}
                  username: {{ grafana_loki_username }}
                url: {{ grafana_loki_url }}
              name: integrations
              positions:
                filename: /tmp/positions.yaml
              scrape_configs:
                # Add here any snippet that belongs to the `logs.configs.scrape_configs` section.
                # For a correct indentation, paste snippets copied from Grafana Cloud at the beginning of the line.
                - job_name: integrations/node_exporter_journal_scrape
                  journal:
                    max_age: 24h
                    labels:
                      instance: {{ ansible_hostname }}
                      job: integrations/node_exporter
                  relabel_configs:
                  - source_labels: ['__journal__systemd_unit']
                    target_label: 'unit'
                  - source_labels: ['__journal__boot_id']
                    target_label: 'boot_id'
                  - source_labels: ['__journal__transport']
                    target_label: 'transport'
                  - source_labels: ['__journal_priority_keyword']
                    target_label: 'level'
                - job_name: integrations/node_exporter_direct_scrape
                  static_configs:
                  - targets:
                    - localhost
                    labels:
                      instance: {{ ansible_hostname }}
                      __path__: /var/log/{syslog,messages,*.log}
                      job: integrations/node_exporter
                - job_name: integrations/docker
                  docker_sd_configs:
                    - host: unix:///var/run/docker.sock
                      refresh_interval: 5s
                  relabel_configs:
                  - action: replace
                    replacement: integrations/docker
                    target_label: job
                  - action: replace
                    replacement: '{{ ansible_hostname }}'
                    target_label: instance
                  - source_labels:
                      - __meta_docker_container_name
                    regex: '/(.*)'
                    target_label: container
                  - source_labels: 
                      - __meta_docker_container_log_stream
                    target_label: stream
          metrics:
            configs:
            - name: integrations
              remote_write:
              - basic_auth:
                  password: {{ grafana_token }}
                  username: {{ grafana_prometheus_username }}
                url: {{ grafana_prometheus_url }}
              scrape_configs:
                # Add here any snippet that belongs to the `metrics.configs.scrape_configs` section.
                # For a correct indentation, paste snippets copied from Grafana Cloud at the beginning of the line.
                - job_name: integrations/nomad
                  metrics_path: /v1/metrics
                  params:
                    format: ['prometheus']
                  static_configs:
                    - targets: ["{{ ansible_hostname }}:4646"]
                - job_name: integrations/traefik
                  static_configs:
                    - targets: ["{{ ansible_hostname }}:8081"]
                - job_name: consul_services
                  consulagent_sd_configs:
                    - refresh_interval: 30s
                      tags: ["prometheus"]
            global:
              scrape_interval: 60s
            wal_directory: /tmp/grafana-agent-wal
      notify: Restart grafana-agent

    - name: Determine available groups
      getent:
        database: group

    - name: Add additional groups (docker etc), to grafana-agent if the groups exists
      user:
        name: "grafana-agent"
        groups: "{{item}}"
        append: yes
      when: item in ansible_facts.getent_group
      with_items:
        - docker
      notify: Restart grafana-agent

    - name: Set ACL for Grafana Agent's user on various files
      ansible.builtin.acl:
        path: "{{ item }}"
        entity: "grafana-agent"
        etype: user
        permissions: r
        state: present
      loop:
        - /var/log/boot.log
        - /var/log/syslog
        - /var/log/auth.log
        - /var/log/ufw.log
        - /var/log/kern.log
        - /var/log/fail2ban.log
      notify: Restart grafana-agent

    - name: Enable Grafana Agent
      service:
        name: grafana-agent
        enabled: yes
      notify: Restart grafana-agent
