---
- name: Disable Grafana Agent
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: Disable Grafana Agent
      service:
        name: grafana-agent
        state: stopped
        enabled: no
      ignore_errors: true

    - package:
        name: grafana-agent
        state: absent
      ignore_errors: true
