---
- name: Setup Grafana Agent
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  handlers:
    - name: Restart grafana-agent
      service: name=grafana-agent state=restarted

  tasks:
    - name: Load encrypted credentials
      community.sops.load_vars:
        file: monitoring_grafana.sops.yaml

    - apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - package:
        name: grafana-agent
        state: latest
      register: grafanapkg
      notify: Restart grafana-agent

    - name: Sync Grafana Cloud Agent Config
      when: grafanapkg.changed
      shell: |
        grafana-agentctl cloud-config \
          -u "{{ grafana_stack_id }}" \
          -p "{{ grafana_api_key }}" \
          -e "{{ grafana_api_url }}" > /etc/grafana-agent.yaml
      notify: Restart grafana-agent

    - name: Replace path
      replace:
        path: /etc/grafana-agent.yaml
        regexp: "<path to json nginx access log>"
        replace: /var/log/nginx/json_access.log
      notify: Restart grafana-agent

    - name: Replace hostname
      replace:
        path: /etc/grafana-agent.yaml
        regexp: "<http_hostname>"
        replace: "{{ ansible_hostname }}"
      notify: Restart grafana-agent

    - name: Replace node_exporter hostname
      replace:
        path: /etc/grafana-agent.yaml
        regexp: "replacement: hostname"
        replace: "replacement: {{ ansible_hostname }}"
      notify: Restart grafana-agent

    - name: Replace hostname to proper value
      replace:
        path: /etc/grafana-agent.yaml
        regexp: "instance: hostname"
        replace: "instance: {{ ansible_hostname }}"
      notify: Restart grafana-agent

    - name: Increase scraping to every 60 seconds
      replace:
        path: /etc/grafana-agent.yaml
        regexp: "scrape_interval: 60s"
        replace: "scrape_interval: 60s"
      notify: Restart grafana-agent

    - name: Setup process_expoter in Grafana
      blockinfile:
        path: /etc/grafana-agent.yaml
        insertafter: "integrations:"
        block: |
          # Process with comment to keep indentation
            process_exporter:
              enabled: true
              process_names:
              - name: "{{ '{{.Comm}}' }}"
                cmdline:
                - '.+'
      notify: Restart grafana-agent

    - name: Enable Grafana Agent
      service:
        name: grafana-agent
        enabled: yes
      notify: Restart grafana-agent
