---
- name: Configure WiFi and Ethernet
  hosts: all
  become: yes

  handlers:
    - name: Reconfigure netplan
      command: sudo netplan apply
      async: 45
      poll: 0

    - name: Restsart resolved
      service:
        name: systemd-resolved
        state: restarted
        enabled: yes

  tasks:
    - name: Load encrypted credentials
      community.sops.load_vars:
        file: wifi.sops.yaml

    - package:
        name:
          - netplan.io
        state: present
      notify: Reconfigure netplan

    - copy:
        dest: /etc/netplan/80-eth0.yaml
        mode: "0600"
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              eth0:
                dhcp4: true
                nameservers:
                  addresses: [1.1.1.1, 1.0.0.1]
      notify: Reconfigure netplan

    - copy:
        dest: /etc/netplan/80-wifi.yaml
        mode: "0600"
        content: |
          network:
            version: 2
            renderer: networkd
            wifis:
              wlan0:
                dhcp4: true
                nameservers:
                  addresses: [1.1.1.1, 1.0.0.1]
                access-points:
                  {{ wifi_networks | to_nice_yaml(indent=8) | indent(8) }}
      notify: Reconfigure netplan

    - name: Delete cloud-init netplan config
      file:
        state: absent
        path: /etc/netplan/50-cloud-init.yaml
      notify: Reconfigure netplan

    ## Fixes DNS Server on 53
    - copy:
        dest: /etc/systemd/resolved.conf
        content: |
          [Resolve]
          DNS=1.1.1.1 [2606:4700:4700::1111]
          FallbackDNS=1.0.0.1 [2606:4700:4700::1001]
          DNSStubListener=no
          DNSOverTLS=yes
      notify: Restsart resolved

    - blockinfile:
        path: /etc/hosts
        marker: "# {mark} ANSIBLE MANAGED Docker DNS github"
        block: |
          {{ lookup('community.general.dig', 'ghcr.io', '@1.1.1.2') }} ghcr.io

    - name: Create symbolic link for resolv.conf
      file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
      ignore_errors: true # Tailscale might have overwritten this
      notify: Restsart resolved
