---
- name: Configure WiFi and Ethernet
  hosts: all
  become: yes

  tasks:
    - name: Load encrypted credentials
      community.sops.load_vars:
        file: wifi.sops.yaml

    - package:
        name:
          - netplan.io
        state: present

    - copy:
        dest: /etc/netplan/80-eth0.yaml
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              eth0:
                dhcp4: true

    - copy:
        dest: /etc/netplan/80-wifi.yaml
        content: |
          network:
            version: 2
            renderer: networkd
            wifis:
              wlan0:
                dhcp4: true
                access-points:
                  {{ wifi_networks | to_nice_yaml }}

    - command: sudo netplan apply
      async: 45
      poll: 0
