---
- name: Configure WiFi and Ethernet
  hosts: all
  become: yes

  handlers:
    - name: Reconfigure netplan
      command: sudo netplan apply
      async: 45
      poll: 0

    - name: Restsart resolved
      service:
        name: systemd-resolved
        state: restarted
        enabled: yes

  tasks:
    - name: Load encrypted credentials
      community.sops.load_vars:
        file: wifi.sops.yaml

    - package:
        name:
          - netplan.io
        state: present
      notify: Reconfigure netplan

    - copy:
        dest: /etc/netplan/80-eth0.yaml
        mode: "0600"
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              eth0:
                dhcp4: true
      notify: Reconfigure netplan

    - copy:
        dest: /etc/netplan/80-wifi.yaml
        mode: "0600"
        content: |
          network:
            version: 2
            renderer: networkd
            wifis:
              wlan0:
                dhcp4: true
                access-points:
                  {{ wifi_networks | to_nice_yaml(indent=8) | indent(8) }}

    - name: Delete cloud-init netplan config
      file:
        state: absent
        path: /etc/netplan/50-cloud-init.yaml

    - command: sudo netplan apply
      async: 45
      poll: 0
