---
- name: Disables OverlayFS on root
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  handlers:
    - name: Reboot
      reboot:
        reboot_timeout: 600
        post_reboot_delay: 30
        pre_reboot_delay: 15

  tasks:
    - name: "Install OverlayFS"
      package:
        name: overlayroot
        state: present
      when: ansible_distribution == 'Ubuntu'
      notify: Reboot

    - name: Force gathering facts
      ansible.builtin.setup:
      delegate_facts: true

    - name: Disable Chroot only when / is mounted on a device
      shell: overlayroot-chroot sed -i -r 's/overlayroot=.*/overlayroot="disabled"/' /etc/overlayroot.conf
      when: not ansible_mounts|json_query('[?mount == `/`].device') and ansible_distribution == 'Ubuntu'
      notify: Reboot
