---
- name: Install software and upgrade dependencies
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  # pre_tasks:
  #   - name: 'Install python'
  #     raw: sudo apt-get -y install python python-apt

  tasks:
    - name: Update packager cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes

    - name: "Install packages"
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - software-properties-common
          - ca-certificates
          - apt-transport-https
          - openssl
          - curl
          - unzip
          - mosh
          - openssh-server
