---
- name: Install software and upgrade dependencies
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install packages"
      package:
        state: latest
        name:
          - acl
          - ca-certificates
          - curl
          - gnupg
          - openssh-server
          - mosh
          - openssl
          - python3
          - software-properties-common
          - ufw
          - unzip
          - yubikey-manager
          - iotop

    - name: Upgrade System Packages
      apt:
        upgrade: full
      when: ansible_os_family == "Debian"

    - name: Stop and disable snapd service
      service:
        name: snapd
        state: stopped
        enabled: no
      ignore_errors: true

    - service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      ignore_errors: true
      loop:
        - snap.lxd.user-daemon.unix.socket
        - snap.lxd.daemon.unix.socket
        - snap.lxd.daemon.unix.socket
        - snapd
        - snapd.socket

    - service:
        name: snap.lxd.activate.service
        state: stopped
        enabled: no
      ignore_errors: true

    - name: Uninstall snapd package
      package:
        name: snapd
        state: absent
