---
- name: Install software and upgrade dependencies
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install packages"
      package:
        state: present
        name:
          - software-properties-common
          - ca-certificates
          - openssl
          - python3
          - gnupg
          - curl
          - unzip
          - screen
          - openssh-server
          - golang
          - podman
          - vim
          - dnsutils

    - name: Upgrade System Packages
      apt:
        upgrade: full
      when: ansible_os_family == "Debian"
