---
- name: Install software and upgrade dependencies
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install packages"
      package:
        state: latest
        name:
          - acl
          - at
          - ca-certificates
          - curl
          - gnupg
          - iotop
          - mosh
          - openssh-server
          - openssl
          - python3
          - retry
          - software-properties-common
          - ufw
          - unzip
          - yubikey-manager
          - iperf3

    - name: Stop and disable snapd service
      service:
        name: snapd
        state: stopped
        enabled: false
      ignore_errors: true

    - service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      ignore_errors: true
      loop:
        - snap.lxd.user-daemon.unix.socket
        - snap.lxd.daemon.unix.socket
        - snap.lxd.daemon.unix.socket
        - snap.lxd.activate.service
        - snapd
        - snapd.socket

    - name: Uninstall snapd package
      package:
        name: snapd
        state: absent

    - service:
        name: atd.service
        state: started
        enabled: true

    - name: Add cron job for pre-fetch upgrade packages
      cron:
        name: "fetch updates weekly"
        user: root
        special_time: "weekly"
        job: echo "apt-get update -y -q ; apt-get upgrade -y -q -d" | batch
