---
- name: Install software and upgrade dependencies
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Update packager cache
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install packages"
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - software-properties-common
          - ca-certificates
          - openssl
          - python3
          - gnupg
          - curl
          - unzip
          - mosh
          - ufw
          - openssh-server
