---
- name: Install software and upgrade dependencies
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install packages"
      package:
        state: latest
        name:
          - acl
          - ca-certificates
          - curl
          - dnsutils
          - gnupg
          - openssh-server
          - openssl
          - python3
          - software-properties-common
          - ufw
          - unzip
          - vim
          - scdaemon
          - pcsc-tools
          - tmux

    - name: Upgrade System Packages
      apt:
        upgrade: full
      when: ansible_os_family == "Debian"

    - name: Stop and disable snapd service
      service:
        name: snapd
        state: stopped
        enabled: no
      ignore_errors: true

    - service:
        name: snap.lxd.activate.service
        state: stopped
        enabled: no
      ignore_errors: true

    - name: Uninstall snapd package
      package:
        name: snapd
        state: absent
