---
- name: Secure SSH (All machines)
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted

  tasks:
    - name: Authorize my keys (GitLab)
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: https://gitlab.com/koalalorenzo.keys

    - name: Authorize my keys (GitHub)
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: https://github.com/koalalorenzo.keys

    - name: Set Max users to 2
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxSessions'
        line: 'MaxSessions 2'
        state: present
        mode: 0644
      notify: Restart ssh

    - name: Deny root
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        mode: 0644
      notify: Restart ssh

    - name: Set interval for alive check to every 20 seconds
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ClientAliveInterval'
        line: 'ClientAliveInterval 20'
        state: present
        mode: 0644
      notify: Restart ssh

    - name: If Alive check failed for 3 consecutive times, drop the connection (1min)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ClientAliveCountMax'
        line: 'ClientAliveCountMax 3'
        state: present
        mode: 0644
      notify: Restart ssh

    - name: Configure SSH on UFW
      ufw:
        rule: allow
        port: 22
        from_ip: 192.168.0.0/16
        log: yes

    - name: Install mosh
      package:
        name: mosh
        state: present

    - name: Configure MOSH on UFW
      ufw:
        rule: allow
        proto: udp
        from_ip: 192.168.0.0/16
        port: '60000:61000'
