---
- name: Setup swap
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: "Install packages"
      package:
        name: dphys-swapfile
        state: present
        update_cache: yes

    - name: Stop swap
      shell: dphys-swapfile swapoff

    - name: Makes sure to set a big swap file
      lineinfile:
        path: /etc/dphys-swapfile
        regexp: '^CONF_SWAPSIZE'
        line: 'CONF_SWAPSIZE=1024'
        state: present
      register: swapsize

    - name: Create & setup swapfile
      shell: dphys-swapfile setup
      when: swapsize.changed

    - name: restart swap
      shell: dphys-swapfile swapon
