---
- name: Install Tailscale Daemon
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - apt_key:
        url: https://pkgs.tailscale.com/stable/raspbian/buster.gpg
        state: present
      when: ansible_os_family == "Debian"

    - apt_repository:
        repo: "deb https://pkgs.tailscale.com/stable/raspbian buster main"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install tailscale package
      package:
        name: tailscale
        state: present
        update_cache: yes

    - sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '1'
        state: present

    - sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Configure SSH on UFW
      ufw:
        rule: allow
        port: 41641
        proto: udp
