---
- name: Install Tailscale Daemon
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars_prompt:
    - name: tailscaleauthkey
      prompt: "Enter Tailscale Auth Key"
      private: yes

  tasks:
    - apt_key:
        url: https://pkgs.tailscale.com/stable/raspbian/buster.gpg
        state: present
      when: ansible_distribution == 'Debian'

    - apt_repository:
        repo: "deb https://pkgs.tailscale.com/stable/raspbian buster main"
        state: present
      when: ansible_distribution == 'Debian'

    - apt_key:
        url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Gets GPG Keyring from Tailscale
      get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: 0644
      when: ansible_distribution == 'Ubuntu'

    - apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install tailscale package
      package:
        name: tailscale
        state: present
        update_cache: yes
      register: tailscale_install

    - sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '1'
        state: present

    - sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Configure Tailscale on UFW
      ufw:
        rule: allow
        port: 41641
        proto: udp

    - name: Allow SSH on Tailscale
      ufw:
        rule: allow
        interface: tailscale0
        direction: in
        port: 22
        proto: tcp
        log: yes

    - name: Configure MOSH on UFW with tailscale
      ufw:
        rule: allow
        interface: tailscale0
        direction: in
        proto: udp
        port: '60000:61000'

    - name: Enable Tailscale
      service:
        name: tailscaled
        enabled: yes

    - name: Setup Tailscale Login
      shell: |
        tailscale up --authkey "{{ tailscaleauthkey }}" \
          --accept-dns="{{ tailscale_accept_dns }}" --accept-routes \
          --advertise-exit-node --advertise-routes="192.168.0.0/24" \
          --ssh --accept-risk=lose-ssh \
          --force-reauth
      ignore_errors: yes

