---
- name: Install Tailscale Daemon
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - apt_key:
        url: https://pkgs.tailscale.com/stable/raspbian/buster.gpg
        state: present
      when: ansible_os_family == "Debian"

    - apt_repository:
        repo: "deb https://pkgs.tailscale.com/stable/raspbian buster main"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install tailscale package
      package:
        name: tailscale
        state: present
        update_cache: yes
      register: tailscale_install

    - sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '1'
        state: present

    - sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Configure Tailscale on UFW
      ufw:
        rule: allow
        port: 41641
        proto: udp

    - name: Allow SSH on Tailscale
      ufw:
        rule: allow
        interface: tailscale0
        direction: in
        port: 22
        proto: tcp
        log: yes

    - name: Configure MOSH on UFW with tailscale
      ufw:
        rule: allow
        interface: tailscale0
        direction: in
        proto: udp
        port: '60000:61000'

    - name: Enable Tailscale
      service:
        name: tailscaled
        enabled: yes

    # - set_fact:
    #     tailscale_authkey: "{{ lookup('community.general.onepassword', 'Tailscale - Reusalbe key', field='credential') }}"

    # - name: Setup Tailscale Login
    #   shell: tailscale up --authkey "{{ tailscale_authkey }}"
