---
- name: Create users and set SSH keys and GPG keys
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted

  tasks:
    - name: Install GnuPG
      package:
        name: gnupg
        state: present

    - name: Set Up Users
      include_tasks: user-single.yaml
      vars:
        username: "{{ item.username }}"
        pubkeys_urls: "{{ item.pubkeys_urls }}"
        email: "{{ item.email }}"
      loop: "{{ system_users }}"

    - name: Download GPG/PGP Keys ( root )
      shell: gpg --recv-keys {{ gpg_key_fingerprints | join(' ') }}
      become: yes
      become_user: root

- name: Sets Root cron jobs
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted

  tasks:
    - name: Uses Bash shell
      cron:
        user: root
        name: SHELL
        env: yes
        job: /bin/bash

    - name: Download GPG/PGP Keys ( root )
      shell: gpg --recv-keys {{ gpg_key_fingerprints | join(' ') }}
      become: yes
      become_user: root

    - name: Adds GPG Key on Cron ( root ) to encrypt messages from cron
      cron:
        user: root
        name: GPG_CMD
        env: yes
        job: ifne /usr/bin/gpg --batch --armor --trust-model always --recipient {{ gpg_key_fingerprints | join (' --recipient ') }} --encrypt

    - name: Adds Email notification
      cron:
        user: "{{ ansible_user }}"
        name: MAILTO
        env: yes
        job: sage.scenery0e@icloud.com

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        line: PermitRootLogin no
        state: present
        mode: 0644
      notify: Restart ssh

    - name: Secure SSH by denying Pi
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "DenyUsers pi"
        state: present
        mode: 0644
      notify: Restart ssh

    - name: Secure SSH by denying root
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "DenyUsers root"
        state: present
        mode: 0644
      notify: Restart ssh
