---
- name: Configure WiFi
  hosts: all
  become: yes

  tasks:
    - name: Load encrypted credentials
      community.sops.load_vars:
        file: wifi.sops.yaml

    - package:
        name:
          - wireless-tools
          - wpasupplicant
        state: present

    - name: Create WiFi configuration file on Ubuntu
      copy:
        dest: /etc/wpa_supplicant/wpa_supplicant.conf
        content: |
          ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
          update_config=1
          country=DK

    - blockinfile:
        path: /etc/wpa_supplicant/wpa_supplicant.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item.ssid }}"
        block: |
          ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
          update_config=1
          country=US

          network={
            ssid="{{ item.ssid }}"
            psk="{{ item.psk }}"
          }
      loop: "{{ wifi_networks }}"

    - service:
        name: networking
        state: restarted
