---
- name: Setup Amazon SSM
  hosts: visma
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Install Amazon SSM package
      apt:
        deb: https://s3.eu-west-1.amazonaws.com/amazon-ssm-eu-west-1/latest/debian_amd64/amazon-ssm-agent.deb
      when: ansible_os_family == "Debian"

    - name: Setup keys for Amazon SSM
      command: sudo amazon-ssm-agent -register -code "{{ assm_code }}" -id "{{ assm_id }}" -region "{{ assm_region }}"
      ignore_errors: yes
