---
- name: Setup Qualys Agent
  hosts: visma
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Create temp directory
      tempfile:
        state: directory
        suffix: ansible-qualys
      register: temp
    - name: Copy QualysCloudAgent.deb
      copy:
        src: ./files/QualysCloudAgent.deb
        dest: "{{ temp.path }}/"
    - name: Install QualysCloudAgent
      apt:
        deb: "{{ temp.path }}/QualysCloudAgent.deb"
      when: ansible_os_family == "Debian"
      ignore_errors: yes
