nordvpn_token: ENC[AES256_GCM,data:NfQnegcRNIztNHmoY9r2b+R/MqCgSOPZjitjCKis/d51tbg4ZYlKywkySQjK6b8Y6jLXX1olpYuxzMn/RtgBSA==,iv:9zAkxaed0wQkMs0kRRzlq537PeHp7YZ4KDeeSCIorVc=,tag:1QbCboMc6fkaW0jPJ1wQtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15qauah7skmftfg5u4z4l526uas5gqaze6k6d09fm7jnga0zzuqtsfy3m5n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNW5ib2ovcXhGZ0hVcjlh
            SE5mSkVONnJsdytwRFliaVFiekExZTBRam5nClpDZ3N2WnpBNDl6cURjQVdHNUR2
            K1M2V3Z5ZWhkdE9PdE5LSlJoRXpaQ0kKLS0tIGNHSXJRYlJvV29iZzN3UVIweklM
            VzFtQUpWMm56RzBTcmh3K25FN0tPQ28KwL5VMDc1TtZH2FbRbwCulELBJrvSVcYt
            8TRQKdTihts/dAIHPezut5xwVledHCUP8J43lcTpebQvXqlxxnLthQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yq5m2qs0ghd87wclpg9vcntql9sxfex06xs6d4efk6n2d80mkp9qrk70yv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNXM1NmIrVHhpZmZWYzNB
            Nk82UVdMVDRtZ2QyRHMvK1grZFZxRGs0ZVRFCjUrdGdlbkU4QVMxN3ZxSlhMd2pq
            bUJJSXJnL2luZlk1MFQ3UlVCOTc2Y3MKLS0tIGJRcUpEUnVSa2U3MDIyRUQrb3NE
            SU5tVmNsU2x0eFZtaHpTcXhzeXlaSGMKB8q8q0V+T8+Vpe8Uyag8Dh4O+irGnkGw
            yxjty7DW8C8vVPM3RxUU6klNv9Ve1uYL/ylK3kUaMWkHdLqjGFCDbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12j6e5yspv9yw7cprqegfprqg39vde3qxkfggscksrneu0pkwju3se80x7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTEdOMmVmdDlHdkR2SlR2
            RUxRNVJ5V3RiOFk3MEErL0JlUUNzRi9jblRzCkRvallJWXQzd0RtS3lvTlV4Zm5z
            M04yT25RclNYR1BuNGtFMUtyNnRkWWMKLS0tIFBPQTJtNjI0ZWFBNStNZzdnRFk4
            RVJFWlJKc1RwOWJFZW5CUnlJbDFaQkEK2Bbm0ZmLk0DsW4kVouwt0netnAigufmt
            4NYOTP1qqWJNhdyk7gy8bMI3kf0lvGabdQilwsKyeOvBCVPPg3MgYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f9uy7mcfdm7skndsa9p5zu9xqfs8hahxtzg75e4vktrkvqc9qu5q89fdzf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTmtWME5tQnhSU1FXTjha
            LzhmRzNIMGVUTmlBSldmeHFtTDRsa3ZxdGk4CjhsR3VjdTBxMlo5bjl0end3L2Mv
            SGtRbHBNYVNHV1ZyMksxWTlsUXNDdFEKLS0tIDdZMHBtdzY2VmFKNVdnOUdvaU5Q
            cUlyZThpaGRZdXZMbGJUWWJjbVM4RlUKfRln4nZuajSjra7B16H5nVyC4foj18jd
            7Sm7hF/xfUmZ/MXqOc7TDwnL4flGFIYjIBkalBYeV3GR0xOg2+A6ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T15:42:43Z"
    mac: ENC[AES256_GCM,data:BX/OmEQ4CsIQ6ZZOFGyRS/oRzPPU5tOsXZ3h9jhrrElqEp3oaflLHS4BDPVrWxW6ZQb/JTDuJ9vOdki9YAxjFT1y+e6IzwQT3BNobwMRTBW5cqPzHQd07GAvqjHU7q8DkbzBr3x/gD6nEr9BYoks8F8o6/8El8v5sHnods9wTlg=,iv:EiM3Au09eKIi+LJCliir0cS/JF/Veq9qZPAzAjudC08=,tag:9Z+tyjYbub4xd+JtYGBX5A==,type:str]
    pgp:
        - created_at: "2024-06-09T18:43:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwEkGKbmunUuAQ/9Fw5i5mPxSbJnbrrp9ZiWBopRXTCvedaoMJaQkKs0tswj
            FtHzN3dkHEzjDK0ynsdrUtuV8ZkMNPFnKKOPQV1hdjvPgdnJiswx8MVzjLiud9DO
            LBGVEa0Utk6Q9Tq1ALIhAIh5ycmGDLJKTDLvRWzlse7Gip1yQr8VySVorII0Ypcr
            BNaKGROS5xLoINYsgfFW2ZJT9p8M2CxIiOWauIrFlARr7OjfD7lZYxJeFGkq4/Qo
            ZvmE2tqHYH1GforhlI7nmCfgpCeiXGVkoF16IqdFLW1dzVm245Zo4sCY+xMKDtLo
            S5QiwZe8pqxTTZSYn13zCDjTfjnMrZezTTR4Z8RZdym7yRbaN8JMy4diaW8Dhgju
            7pIJqY/D0ShI22b9Pe5RFgYja0HGJYStgzksKoX4c39cEs183JXrsSeMPCCLL/DJ
            aCN7XOP1WshlOX1lAF7OHdhXf7rWRqv7uQLZtUWhpw/GRAT2mID08ZHbMENZthJY
            DcUtqByRt5VgyeVN59XHpVadqe4BsTlrTf0CX0GAhmlYfm+onyMG4EbhdArVN5GY
            LpHPwpBjZ/ZIfDZ26ip2cPy+vrQB62MaRpu+TIibP4mkoRgCIpTKCGmxLWlJJF7H
            +CTq1JFoObsgpfLyiCQ2dSR9XknYnqPfQkCMBvhSlVyfB8qkKLcVCuy+rwq3ENfS
            XgF+y8ybDtkcUvyrvHxnSWHyzFrsf5XC133+hBnc+9AG1nB5/DECbOm4GYIFH9/x
            I0wqaAfBoNTYm5Ey5jtCyB07wizqSvfshTuzhhbbT1i6V2/lmyNL4fXwKfEf/Hw=
            =/2GE
            -----END PGP MESSAGE-----
          fp: 73880ECAF69EC2ED44CE5889502BFB12D0B5295F
    unencrypted_suffix: _unencrypted
    version: 3.8.1
