nordvpn_token: ENC[AES256_GCM,data:NfQnegcRNIztNHmoY9r2b+R/MqCgSOPZjitjCKis/d51tbg4ZYlKywkySQjK6b8Y6jLXX1olpYuxzMn/RtgBSA==,iv:9zAkxaed0wQkMs0kRRzlq537PeHp7YZ4KDeeSCIorVc=,tag:1QbCboMc6fkaW0jPJ1wQtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15qauah7skmftfg5u4z4l526uas5gqaze6k6d09fm7jnga0zzuqtsfy3m5n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZW9mbkJHc3N2RjBUdzQ4
            OElMZzBqZnZtOWpnVkNHNFJXbmxBUmxtUVhNClBEbk5DZmpxeUI5azJRYitwOWJh
            Z2U2NGhGRXBjSUJGdnVPaHEwbmNLY3MKLS0tIFhxNXF0bUcwbE0zR25tVnpwbnM2
            MXA0Znl1S2lSN3VYdlBBSGtXT3VhQ0UKL7OOOulCD4g99y2o1QMOnJs6f3PI4BMD
            tJmEzkG+gl8X3W1ncEFc2ltUPG0qKWfejxgKkpYI1moX/wG91sUYeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12gjnss76aeqqly8jwh05c3na44r6nu5ws04v07xedj9fwf38letsewvd6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ajZsRzBjQjl4VEFHT0ZE
            cGEzZTZoOEVQQ1BMWG9QQ2VzYmFMRGpLRVZFCmFDaXdCUGlueW5NeGk4aSthMXJv
            WUlKUHozbytYUzZVdTlmcXNMbFhwZXcKLS0tIEFMbzYzSkFHTkJHTFh6YlEyR1RG
            cVdha091ODZWaWl1K3VOenhWRU9DY2MKRbaOTrb0lvBipauAOvLr1iMm3Ig8KVav
            ShHWV9ZTjAQl7YFcfwWsUlb2rpYNq6S4NzHoRuM5iy5+DAqirBVlsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dyqrgtfmayzq4a9hsd743jzlkmty0ac4q8wwjggwadumzy3hj3us86m32q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOWh6dmtDNEVOeWhXekRm
            Z1J3QUJCN3JrZDQwTHpkc3hsV1JCNmJKMVJjCnA2bEFWcWtScDN6cmM4VXl4T0tR
            L1JjSC9HK3gxU2VWZTdZVmZTZXl1M28KLS0tIG1IU2tFMmtMMnVkaFA4azljanJF
            SU5uYjBaaGdQemdQTnhCdnRxWmIwRW8Ki/9BG8JZvXNC2TYjiRab15Jx0o1hWCHp
            oEdXfD210tuHNv5KPX4IgldQ5oKAK0sTkqaK6o7pJh4NppVzXofuNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f9uy7mcfdm7skndsa9p5zu9xqfs8hahxtzg75e4vktrkvqc9qu5q89fdzf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieXFJRGRldU45WGJNQURj
            ZmNHQjVxQm5mekJ5ajRLNTQ4NVRCVGo1N0RnCldWNWVRYWRONEdMenp2bXFuK3Vl
            THdJdXduTUsvQWgzdGZqYlBvM2Vxd0EKLS0tIDVQRC9tWTdyeCttZ3VIY2ZzTHhs
            dWIwR2gvNGNSeU9rM3pvN25sNGdGbXMKuchsrGSe6zcDoQyKx014Rpu4gKpt1C/4
            8O6DKt5+3ea/4lsKNaL6cgH4h0PgmmpxOIpmAechNlf/OANoGLGC6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age123602hjzp7w95ndcfhz23dj7mza8fdm5kav2ttsyg5uk7qq39c8sxs5tyy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTi9rYzFJdnVqdllxUlEz
            K2NORU1wZG92YTFkQk94Q2ZqWmJRNzRmMFJzCmZNdkN1WVZqK1RVejJHUVBPeWoy
            b2h0L0NkTmJ5cWU4cHRJVGJXNWR4Qk0KLS0tIDRlV0hWL0U2MStncDBCY3JLcnVh
            NFNOS1IrM09oNmVPcHFIN2V4eEprZlEKWN6RtQ/5At+q/dcjh5gasazBT9SsvD44
            SNbgCDdd6sUFjaNMIS0uBJf40vn5rUTQ9qlF3TcHUWKhowRQ02Uy3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age165zwkwyyzg4vhg3a2qt6ucje50y7jupakwuaxm66n26ch2vk9yqq2xcz6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMVRqRXJKYVdmTWVHeW01
            ZWlrbjBVMnZNQVJOMDQwNGJUNkcrZXI0WDN3CkhMckRucFpWckJXSnZoSkk3aDJl
            cCswTDZTWms0Z2RQQ1V0Vy9CQ2tSMWMKLS0tIG5JR2RVMHhGOXBrSVVnWWZ2cW4y
            bUdOL0NmWDZxTHp0UHgzVG9HaWxzeEkKOt0d+priLikr/fG6SAwJR7N8kcJLXqFh
            jzuI3ZPV+pX8V4EA5Vce71KY2+7RMTG21pa/yzlonCnNNvRjkYjt3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T15:42:43Z"
    mac: ENC[AES256_GCM,data:BX/OmEQ4CsIQ6ZZOFGyRS/oRzPPU5tOsXZ3h9jhrrElqEp3oaflLHS4BDPVrWxW6ZQb/JTDuJ9vOdki9YAxjFT1y+e6IzwQT3BNobwMRTBW5cqPzHQd07GAvqjHU7q8DkbzBr3x/gD6nEr9BYoks8F8o6/8El8v5sHnods9wTlg=,iv:EiM3Au09eKIi+LJCliir0cS/JF/Veq9qZPAzAjudC08=,tag:9Z+tyjYbub4xd+JtYGBX5A==,type:str]
    pgp:
        - created_at: "2024-05-06T07:56:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwEkGKbmunUuARAAsx9cK2gzIuljm+5PEhOtuPmqrQHiFB3WyaM1htEh+xq5
            TUWcJFxuKfNi2UVZNSTEVl5YUNtMIxqy/rBpQZVb5DSMcLgbGT4ueyp2tSCCEhRp
            UzT9sqWukpbOHCMnTWtU4XTqzODMZlxUv/hfVTLSGVO/jDimySXoISfmcYRmjK/p
            9PSx8dh/y8AYJs5V7ZDvTT3MGMC15pBa3KDb2cTYC3DD7NLvA4sSPWxjBKeQt19V
            aVhdzhP4m7BDl4juR3g818zNnhY2xur9pdlx6V+pHyB3bcBw1KQB+E+vXIivnvPu
            fqQca1aB0Yl+zw2tyyGwK+tz/VyUwSDkkOHn3Yc7os4ywncuMV4NrlJL847gO7pN
            tgugbVmfPWBXsXR20MYJscUEs1hcDA5wiHiuYkkWa9cz07ZJKDLMjyDKPgPSC5sd
            HbQOJlHXflQbP0aZ1oVCzQ9drDVXjkPCa2oT9daJXrobcDji/K5TW6qoz4sdSZIA
            5+QOarO/Yt8RMOMz76z3G4Oq2ycObPKUx6PioCb3+IREEq6e6NQi1GesFTwcCV5d
            qSa/tORHy8yZ9J9Ui2TseREA4cewMyYOsW8SD2rSSSVqa3wuTxe4ioH3RnL1p/mU
            rkTcaHd6BYTeHr4RH3sTsT7AyBrZyXNl7yJNI+tzZb7Z1v0wxqgp+1gayLwaSpLS
            XgHV7TCtNIdNNjMVZ6tT5d571gDGUQLjyQvLBYp2mcVQzzZ6GyiRB7B1QK1vLdxQ
            f1t3O3t0x4MLwhd+KGpjop7l7aviSAIf2RShLfFp1ikW+9xwumjT3oBQhSUhEI0=
            =SzpD
            -----END PGP MESSAGE-----
          fp: 73880ECAF69EC2ED44CE5889502BFB12D0B5295F
    unencrypted_suffix: _unencrypted
    version: 3.8.1
