zfs_personal_pwd: ENC[AES256_GCM,data:+Ty9Xzx0HLI7u23JQajbogeRXz+kyi23FvqA4YZqvde7SMW6WaVYihH75hW8hXL4nkz7W2n7RpIhj4n2XLStGw==,iv:VMNhHK8A5nErS3idvOlAQkuRHXoZzHjngv3EU4HBFbs=,tag:vLBsE12NeA3OEaGglMLweA==,type:str]
zfs_backups_pwd: ENC[AES256_GCM,data:aVs2zlI9/UuealLpBon2XsmPoXfitbQn5dTI9N6Bh3+WOiVwR3yQE/q8XdJ1cn6SmQCYsk4s8gcJcvjls3ykTQ==,iv:Dl4ZAXnla8ki3GvDOB//fj8ghejZ2Qdh1QIY2XyDG6w=,tag:767nSykrBKxgSD4quAnxlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hv77jtx2x5dczummreqqksw0nr54nqz6mdpwljdveme2lz8csp7qjhnr50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUlJRTkZzUFpBUmpJaUdp
            WmQvWWI5TDNEUGRUV3BCMGNuQXQzWEJUbTE4Clc2ejVFbk9jb3ViUThrRzZCSlB6
            akpSTFdGblhLdWxWSTNINzRKVUw4SFEKLS0tIHpTY0phak5OaHdORWFvWld4K0tM
            NjI0WWg2dzNWd1h5RkE0eU01M2J0Y0EKe6lVkrAOa0Q/WPNiAHWTu72Q3fZCO9Qr
            x6opavqdnLaxMljbFcm6tRV7mEQIlokFRRb5o69nD58S76EAeZJn6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15qauah7skmftfg5u4z4l526uas5gqaze6k6d09fm7jnga0zzuqtsfy3m5n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OVJ3Ty93T3ZOSE40YWNq
            UWhaNlBVQ1NUanZIUjRaSjdXTnFSZEtaUndjCjg5MTNPeVRLVjB1OGhLZVVYUEg4
            VVBqM3lUVlRkR0d6ZHBBdkFxNDE4TjQKLS0tIHkwUlgwVDJ3bmpoaE1GK3NOQ05i
            SUJYdWJISGphWCs5QmFVZUYzSU44NDQKBp/XoqPoCBj+eckievZad5ytBZXIowle
            z5fgvoXCRAVyGHbJ/9Id/DdoZgXHEmPXfTHKaF9jz7Z0MNRztQa17A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12gjnss76aeqqly8jwh05c3na44r6nu5ws04v07xedj9fwf38letsewvd6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWlFDNDJBZlJzUnlUcitX
            K0V4ZDVsd3V5R25aN3N4WFdsdjlQVzQ1V24wCkxPY1RUK0Q1MzU4TnR4eURyejRU
            OTMrVjY4UzVkSS80MmV1NVQ1L0pNZFUKLS0tIHV0cTgrK3YycEJENHFiYjJTMG9M
            cm1yelk5enlUVFlkMGtSKzQxQjhqQ1UKeHcx85+BUAgh30zJZRJPvziwwucYB75G
            Sepb00uDNOXVoRykrPhI1QUK1PjCX5KUfkm6PYbHG1o8yVVC9GCLvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dyqrgtfmayzq4a9hsd743jzlkmty0ac4q8wwjggwadumzy3hj3us86m32q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycFMrRk1WUjlxUUlKWGQ0
            dmlpcER6UkFnOE10eVBBU1BXVUhodnJTblc0CjVucndWcCszcVl1QkZoOUVLbk5o
            SVFkTEtlS3JrdDZBdnZ6WWlHYUFCY2MKLS0tIGJHNVFmSDJuaUFDOFEwRWpoMGZQ
            eHliNlArTEsrZmNPS0lkbzZLeTBUcWcK6VfvRe2STlsPuSsIW1Wqod/D9VeXbdl6
            1ZidMH3k5bpfgZN7zwbxZebkElXYDjw2otJQ8mWw9UOa78HlPECC8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f9uy7mcfdm7skndsa9p5zu9xqfs8hahxtzg75e4vktrkvqc9qu5q89fdzf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZHUrQ0ZwV3pFUFpYRWVV
            dTFwd0Y3MmdCZnVhcy9KUjBKRFpDVmNBUFFrCkdLUW5JeFNJeGJsdUxISUhVNWM2
            TE1pMXo1eWNuKy9xVk5kVHk0T0hoNjAKLS0tIDhDQ0R3c0N6a0hub1BJNGk2WHJm
            dGg4OHJKSE5rY3M4REhja0dwNTdZYm8KgPW47Fa9kM8yY6RAsWbbm7uvy7dAIzhQ
            Iqai0+XCS+qJ0QmO+jEo+JzjVEc448QR+14mu8vtzGLPsOroVCBbEA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age123602hjzp7w95ndcfhz23dj7mza8fdm5kav2ttsyg5uk7qq39c8sxs5tyy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZHFjWmdTc1lXeDN0Y3Yy
            R2hyQ29JMktPMVUxbVl5RDhITjdxWHhMQlFjCkRhRlR0aW9YSHVVQWUvbHdzUnZX
            eEpaNTNiVHpYdkI4Y0Y2eW9Sby9lV1UKLS0tIHR4d1VMTytjQ1hzN21SMjMvYWVT
            UEZBK0RSZStGcHFNZnhWcHgxN1d0TG8K5iJYe+tMFPb0iU0dq4JsaJ//GUofj0uO
            CrPbzafNExIwvqMe/z7p4mVGpvdAOXd/gMWqtSQTMXy4LDBtel6pcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xrwvrmq8r4w47ka64ptx8qkc0zaek9056gmen9tkrwvdk08p5pfq7c78h3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd0VybWJuaEthVk8zV25r
            c3BrZmRDNUVpV1gyRmtpV01aQ1orTU1yNzJVCndVeG1PaHJFdHJXOUhPb0NVQjd6
            QkFFSUhSME9ycHRDN1JTby9jekhCUUUKLS0tIDZOQ01Wc01tYndMRDkwZHVWdGpr
            TTNLb09CSERpSnV2YTNiYkJva0hNWHcKRL44LoZmg/r/dq51nQxPp2EY9y1U9Zdf
            kqGwqUPs1MZGRom2gJHPXsMlwY/3YdxuR0NI7EqO1T2WNIc2pZinAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T15:42:39Z"
    mac: ENC[AES256_GCM,data:rjrgxZoKCNn1jQe4xRDOxVHryEpIKejG64bkePUTIQSyxXqvDbOFKlsffOCp05trZl4kHtWpYMJtekkOuSMmZeBioxKTmQrC0XNbxY6LGOD8wv+AvbPZ0ZVOCfU1DPUsZDoCMOvlI1EKMNALsF/VTD324DKb/U86++a4rNryzOM=,iv:Q45Zap7WzILMMd8qN1A60hvVRc5q80/L3DAc0VazmEc=,tag:2Xmt/FaBMNgX+kI5h4Cjvw==,type:str]
    pgp:
        - created_at: "2024-05-05T15:42:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwEkGKbmunUuARAA5WT7lxPfVMfNFQLT0yPNZ9bfgSi3hvXEP9iQsuEJ3K0m
            KQHH4m8xNPJWCZ8cre1BpVRnk1t9zXRnTZ0OTwCzZPErfBsk+Dc8i0AWiTi9dyj5
            Yjq88p9pPiW6htEtwEEWgmFBeVvD/SDaNTTd+YrcTJPbBHqMwsnESO25TFxLx4fm
            zGmFGDKgKQ68ssFfrHxipcbX9Y6oBfBfs8laPa764cpnNuqM5/Dj42D13NIHGcRW
            SETE7WMPd7lynfn00TojaH2RHup0fS6f5sZ0MLgee+olxdT8lYaux7Kavee5ceNt
            Ves2EN+WI9XyZ68XQrl6+ujfTmi5HIlkRlDmN0u7v2ebLJOQHRiM0KKTGhZVC2Ye
            qWxPgrurXbzbXWt6g/7IJxBXYAeAA4y3WrCPcEYGswo2LfmxdSgS8PrMbH0n9/L4
            HWzZ3N8xqFzODkF5N//b/6jvr8ZpM2dZmD/+Lp0aRUuFHLT/t+Dijl6UCQ75/TBT
            wzHNw3gS5hay8ZkWp3/uHeVlXOICvyoV8XAnGhBW6jEHsxK3McZVKXBkPieGHcVX
            15LWpUNNjRIwNpI8swiRXgllnYj08XuZeMTTEIiyG6tRko6m7mHap1GXfgeZr/A6
            TwQB/mBwJ3KZhFxnjkYNqUvwSOXqgD2kQKvIlyY5bFasHcKdU77VI+wBS0tzIcjS
            XgEp61w3jAsRrjMgISeOSidJgSpnYtq9tBpiRvlEbqvBsBfGzzElCapfwM9KqBpd
            cF5AKvMxLITI0Ka1dkmoFE1bv9o3DNz/J37woElQkv8FL91/QcxzqQ2Sj/ZUhgw=
            =hj4S
            -----END PGP MESSAGE-----
          fp: 73880ECAF69EC2ED44CE5889502BFB12D0B5295F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
