zfs_personal_pwd: ENC[AES256_GCM,data:+Ty9Xzx0HLI7u23JQajbogeRXz+kyi23FvqA4YZqvde7SMW6WaVYihH75hW8hXL4nkz7W2n7RpIhj4n2XLStGw==,iv:VMNhHK8A5nErS3idvOlAQkuRHXoZzHjngv3EU4HBFbs=,tag:vLBsE12NeA3OEaGglMLweA==,type:str]
zfs_backups_pwd: ENC[AES256_GCM,data:aVs2zlI9/UuealLpBon2XsmPoXfitbQn5dTI9N6Bh3+WOiVwR3yQE/q8XdJ1cn6SmQCYsk4s8gcJcvjls3ykTQ==,iv:Dl4ZAXnla8ki3GvDOB//fj8ghejZ2Qdh1QIY2XyDG6w=,tag:767nSykrBKxgSD4quAnxlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15qauah7skmftfg5u4z4l526uas5gqaze6k6d09fm7jnga0zzuqtsfy3m5n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSUxzSTB1b0s0ay9KU3dr
            TEtRbU1UN3IzdDNCSDdiU1BLWGdiZ3NPZVJzClk4SXowemp3YUFCYWo4VmxIMmtx
            RitrV0RGUlZWQ1RwVzdHYkdVNU44M28KLS0tIHlHa25KcjJiL2wrWitpaFA4bGI2
            SkNCdHpNQmIwWm13azgwTnNYZXVZV1UKRNHtnbVWxodF2SdyoFCqlnZXmJHuBumT
            o8capKL7Ajz9Su/N0qFLyLuNvmEEUdndfRcmk01dUGzuRMTYez4/Mg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12gjnss76aeqqly8jwh05c3na44r6nu5ws04v07xedj9fwf38letsewvd6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROW5YNlVudlhnNDB4R01q
            UERPb2l4R2NqUWhqejZ1REh5ZDVZckI3cUV3ClF0N2l5SjdZYzlpWXRSZHcwUmhJ
            aGt3SGFzV3RGRXBnbWcvdVpxVjQySDgKLS0tIHV0bDRHR3prdlZyMVowbEFlVXF0
            KzljY0gzb1R3SUU2VzMxOWkxazlGZTAKDVtq4D9muKTir7oMMcFPtiigZU5wiyzy
            8L4+IX0PgaqeuRqLrbB20zzMMEHHXrZzEnt4n8ObMqut2g47atXjWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dyqrgtfmayzq4a9hsd743jzlkmty0ac4q8wwjggwadumzy3hj3us86m32q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRSszNXhJaGZOWGFHemtE
            WW4rTEJ2bVMzTStIVDhYb2FZcFFhVHF4YzFnCmFIZENDRGNYbmxTMU9WNkl6K2Rq
            TVdkOEpIRVBxc3RUU2dVaE1ESExhajAKLS0tIHhWRGRpdGwxWVZtY29QRWk3Vjhl
            Y1lTTk1pOC9UUGl6L1Q5N3k2bGpkV2sKqEM2H6PXFy+OLBjPmvkbC8iMJmfcQPs5
            v0qtSbjVcjo3sjkGJ/FErd+6uJ4LOtjMG5i+mOxb0jiEZSlVuhq3UA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f9uy7mcfdm7skndsa9p5zu9xqfs8hahxtzg75e4vktrkvqc9qu5q89fdzf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZHd1VEF0cXpGeFB0MjMz
            MmhEa2ErQ0RjOHpPWGZpcVJsMVVmci9aclFNCjc2dzlUQkdjVzc2aVNGWjlzQmpE
            YzJMWXlqeUEvRFR0VjgxN0tPNkcwRHMKLS0tIGM0MVdMZWovTmFIWUF4ajI3Mldu
            Zks1K2VqOVB6a2Q2WVpkdjVFUFp5WmsKKJ3kel0ihwWCqPNHDUMSBgcm9m55sRkz
            OZVSMJnlS9Lqe/9oDUwO8gZAEBOkEqs8JMtDBOU99Bqls9yQVH1izQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age123602hjzp7w95ndcfhz23dj7mza8fdm5kav2ttsyg5uk7qq39c8sxs5tyy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSTM3ZHZIRXdhb1FlcGk0
            L3FsbUVzemZKN2ZmczJsei9OTUw1QStzUkNrCmJ6eUl0bHVRUVlNbEtoNDgxV3d3
            b3dKamlMcm1XQmhMZENRanpGdDN1RUkKLS0tIDJOS2pTUGFjekxRdEV6RENBOWpj
            NDZDRTd4RFdxS3J5bDFORGcrSnFQOEEKPu5cnfV6B51qbB/LbkMTdOfFa7Ydz5+L
            n36iuirm+ZNeu6sYnjkBmOCY4lKGFvRJ+ZDBh5RbuKWIXcmDbmvNcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xrwvrmq8r4w47ka64ptx8qkc0zaek9056gmen9tkrwvdk08p5pfq7c78h3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPejd5aFM1ZHRHVWhJSmlT
            S1EwRHBPWXhLQngrcE1yOWZrbGIreUxjMVQwCkh6QkR6TnZ2OWtCcS9kMGhmZ1Ax
            eVgyUFNZUm5DZ3dVVHhEU1RieHlrVncKLS0tIFYwMU5IWGxxSXFIVTBHRFNYTHJt
            VUxlU3g5Ky9mT1NBVno0UGxLT2IxbjAKbyx1NVwy8uX1SdRpvqF/N2Wuw196PTZf
            9Qxfy0oMBI0EKFWQ2GhMpCpc1iwXycFufM2MF47TZR+ZZ1fwqQ3Vtw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age165zwkwyyzg4vhg3a2qt6ucje50y7jupakwuaxm66n26ch2vk9yqq2xcz6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dHNlVEhjazFLTHk4d1lG
            UndBVkI1NzlCeEJ3MmlBNElqQitROC9INFFBCkx4OTVKcTNaa1FhZmxDa1Baeld0
            K3J4b0RlSlczWFg3S2NmbUw0cjhsdlEKLS0tIDZaeDg5ckhvV041WkNjRkRVbExl
            YWpVSkwrNXNPWStYVFZmWjNpTVZ1ZGMKL03a5klRBSdsYWuONsnJkjGCIPia+6tD
            deGnFQH1YBnUJmrwtzpQ5VBaMZ76+ZtMFvksGIOMu+f7FTSXhtmYyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T15:42:39Z"
    mac: ENC[AES256_GCM,data:rjrgxZoKCNn1jQe4xRDOxVHryEpIKejG64bkePUTIQSyxXqvDbOFKlsffOCp05trZl4kHtWpYMJtekkOuSMmZeBioxKTmQrC0XNbxY6LGOD8wv+AvbPZ0ZVOCfU1DPUsZDoCMOvlI1EKMNALsF/VTD324DKb/U86++a4rNryzOM=,iv:Q45Zap7WzILMMd8qN1A60hvVRc5q80/L3DAc0VazmEc=,tag:2Xmt/FaBMNgX+kI5h4Cjvw==,type:str]
    pgp:
        - created_at: "2024-05-05T17:49:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwEkGKbmunUuAQ/9GSAvSty0pKo3cky1C4ZfiQa6vzqZX1IXcDcXcNHHFjb4
            dFpOa6wagejt1eGV+OJhw2X/PbOE9Uh+zKdtC5HWS0ODC3Ai3YyUkVuEepZV2Ts7
            s/laccPHPVXbcEIR++uzNgg/SOH3ElOyHIyYplKeBgtZ0lejhFUbDuxDdCUB8BTn
            dUfWKlf0I5WLiYrx+/FPMpmqljZOjVkWA9J49nFwEqXhFdx6+iedHo5DeKDNu4Qr
            SyYLTXeN8BTO7WSPUKDgpCsRN4IW3L3owOa6n/iVQ8DEoXVc2ajBG/mkbkLoRHRc
            A1m1Hv+Tpx1BmDv9n31MYLai9w+zcXj0S6GZNecl9rHcUS/HePM8yA3Cn8wWDnrv
            tgbQY4C3GTxvn5e2rewoRR2la4PIkNO3EWk8m+AvRtwrLavx/x72LzE5FpjND02e
            k2Ddm55cUbypNYnVMcCndR/QKv7+kEi9U+UCHsa3zzXmyVg5zOirHHE6O0UFSeyS
            cPiL+Rb2hsbTIDYhWJk9goyV5Svx3fyOZ1jbLLxAReKHsc5tgwylYEIDf7vJqCar
            SCJnxMvnqprdCUu0tNRUl2yWDCM4MKgXWJzwRuQBUCxdhYP2SfDkFFO5/8amz8gp
            a+FJOEpwUoJGa9cbmIfwXUFExMEK9j94/ZQAXFdX5F+GxP363wMUWJmYiU0xD1HS
            XgHXnYFmYJ79qOBOmi1J1kK79m+5t1OzkzjKdhTRUa1Ajw+rXadiaR3ourC3Vj4M
            /3R1UdVnKWDBn0LSVA7VzJS4wMGwp/fWCnm6EfrkWBIov78m97b9DRIr7NTSIgs=
            =0Pd7
            -----END PGP MESSAGE-----
          fp: 73880ECAF69EC2ED44CE5889502BFB12D0B5295F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
