zfs_personal_pwd: ENC[AES256_GCM,data:+Ty9Xzx0HLI7u23JQajbogeRXz+kyi23FvqA4YZqvde7SMW6WaVYihH75hW8hXL4nkz7W2n7RpIhj4n2XLStGw==,iv:VMNhHK8A5nErS3idvOlAQkuRHXoZzHjngv3EU4HBFbs=,tag:vLBsE12NeA3OEaGglMLweA==,type:str]
zfs_backups_pwd: ENC[AES256_GCM,data:aVs2zlI9/UuealLpBon2XsmPoXfitbQn5dTI9N6Bh3+WOiVwR3yQE/q8XdJ1cn6SmQCYsk4s8gcJcvjls3ykTQ==,iv:Dl4ZAXnla8ki3GvDOB//fj8ghejZ2Qdh1QIY2XyDG6w=,tag:767nSykrBKxgSD4quAnxlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15qauah7skmftfg5u4z4l526uas5gqaze6k6d09fm7jnga0zzuqtsfy3m5n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJakNYcmhFTWNuZ2g1d3NR
            aTUyUEtFS01vbVBka1RhQTh0MVVGakNPU3lZCkljQ2FjS3Jxb3VGR2hhd2hrMVFO
            Q0piOFVjaUhqRDVET2ptcE9KVEMwNG8KLS0tIG16eG5jRG52ZGF5VTF0c2tpOTZs
            UDJDcnhmRzdGNllVL1RXSW9LcC9hY28Kz8nMgoJkkIKlKnLNQARE/xnQomuBRfNT
            wPKJNJmvgKbGY5V7eKlgNIEPMJWX5xI5FTPkxfwOZtW//XssH9ip0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12gjnss76aeqqly8jwh05c3na44r6nu5ws04v07xedj9fwf38letsewvd6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxd21qM0N3czhwcm9IcWs2
            VUpNMlhRVTFhWnYyRlpnRXh2cUJHbSthUW5ZCnJPQk9kOG5hemJsaGFsQzVhb0VB
            bnRNMU1LUkpPOWxXdEVWTmdmaVB5QkEKLS0tIFJUeTBTamR0T2VNcmxTdUJGZE1o
            M2Q3Q1lleFFvUllCY3VaRDdOcWxVWHMKTv20r7y/uzRr5eZYEm0do54SSR/LpVvm
            lETUnIc5XoXcW1qhOQ3/pVpqsuBlwVzQACZgKySBYYy+iZC7yqQh8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dyqrgtfmayzq4a9hsd743jzlkmty0ac4q8wwjggwadumzy3hj3us86m32q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZmZ4RytuMDloSjhjTVZi
            dUFTdk40eUljMnlaVnJIUG96OVgwSExvckJZCllkWE5WRnpJSGVyVDdoTDI0Q0tm
            bSs1SUwxVEZzU0hDUXJvZEFVbnZCYUkKLS0tIFZzdUhtSVRrTUJ5SXZkeGNXL3pn
            dWZCN3V2SW5lNkZXb2h1dHZ5VGxkcGsKg6dOPwib7MTwCGvCQZ8yyiy8mMduljJx
            S0g0AVz9Pg9G0x3EY06JMFYPlKNZnpzbv4mhKQPFM+0RW4VBBs5q0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f9uy7mcfdm7skndsa9p5zu9xqfs8hahxtzg75e4vktrkvqc9qu5q89fdzf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV0FodlhCb08yeEN6K3M4
            aTFCNmpHQ0F3eGFGVytDcVdTbUo1d2tyU0RjCk1WY2hYTGY5OU5CSVlnYzEwMDl0
            TitFMEhsOGVwR205Y1BDWEtYTEZua2sKLS0tIFFJYiszV1BsL2QxcFRTUGVKZVRh
            RzFicDMwRUVMczZjdm5xcjE2YUsyR3cKKg7Gv385q9bIWCQfhtNly7NBBCtSpszc
            9su/lGmbb6p7/EPTRr8OKswFBoiZHKWhaqMZ9YR2Z6BKolMySRAzng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age123602hjzp7w95ndcfhz23dj7mza8fdm5kav2ttsyg5uk7qq39c8sxs5tyy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeUpjQlFYbmswbXVBYStx
            R29vL2lOSGVyVDBybHlhbWozZDRiTmtKVkJNCkZCWnlULzhsbWdzY0w0bmJWQ2px
            enVVd1FFVFdNWDJBejc5MUlaVzdUZTQKLS0tIHArSjhodFJqbmRKb0U5RDN5Skty
            dUdPUlZWM2d2OS9GdUorZVdObDhpZ1EKZ+MXyBIyyUfTs8lfzStXS2bntJsebRLu
            bqavnXpXOTqiym0xf/W7jfuAJrbQceSv/Fpi9vYBsekfPIzfLccfqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xrwvrmq8r4w47ka64ptx8qkc0zaek9056gmen9tkrwvdk08p5pfq7c78h3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Z3BYWEFsMWdsV01QMUlM
            bnRIbndCS2kyam5XdEtvdDR4ZGRPc0l6SEVZCmRzUUc5cWMwWnk4SXZGSExISWd5
            WnNOdW5vdmM3RUlXSXRGV3BCVjRkK0EKLS0tIDc3Z052YmZpbnBFTlhnUGlYbHhv
            eEZYeFBBK2I4cTlBVjQvWWlpVU1iOGcKQDn3kckrZ92ayPJFbJxHzDJzC5lL6l/1
            Trf9lLnCH16FMawKa0N2p1hB5wR91Ujw/bSNgN0Jb9nj+2x6GdAHAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T15:42:39Z"
    mac: ENC[AES256_GCM,data:rjrgxZoKCNn1jQe4xRDOxVHryEpIKejG64bkePUTIQSyxXqvDbOFKlsffOCp05trZl4kHtWpYMJtekkOuSMmZeBioxKTmQrC0XNbxY6LGOD8wv+AvbPZ0ZVOCfU1DPUsZDoCMOvlI1EKMNALsF/VTD324DKb/U86++a4rNryzOM=,iv:Q45Zap7WzILMMd8qN1A60hvVRc5q80/L3DAc0VazmEc=,tag:2Xmt/FaBMNgX+kI5h4Cjvw==,type:str]
    pgp:
        - created_at: "2024-05-05T16:06:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwEkGKbmunUuAQ//dC/2z8gExiuFTjXmFLY190HkX1ILKjgFpRkuKAcVxazz
            c8kJRPkWF0Bu1sCHWW+rIBJLceLhlBVIliME87ZP2kq5Z3wIoraYu2dgt5xD7aEz
            a5fuFV9qdGUl32yMeOrLv+bAfzpFqIQ+oiRNy7RKr7h5TROQZQt6Fod7vUPUJ7h2
            JT+iBcQL6G5rz/f68hs8wzKOC02/wpdg7wuNFiYPGw3Wjy62Gc2LAXmiK9lA9nge
            5ar0TomCOQnvLj6L0njH+IUj6RO/z+rxB1XNtgNX7yQEUd5MZ9OAcixdmzfP/1+9
            fPFZ5MtTHJoNxqKGA9xMQlW5NGE8xeDA0l8qkcYOkAP35hxEIH46Z3GkMGwL6y0k
            dXLTOC57hT0RZafDyPbb1kWXKHzbCnmHaUKX/YqLK2gEzXKNdfn9ppLzIz4F5JbR
            MPASDAsMCHahdkc4W2fdTNjVLkDbO/1HDMYmGk6fxlN/lBHMsuw7h4LuuMsxs6hk
            BcuBHjJU7Niwq/ghGveLznb5w++K9fw/9vdSTDNPm/FQPSSDhGlXuYuKdwDk/IVs
            9mq1LKglHRUPIWtbGF62R3Wcd8qJWkCmRrQTR0cb7GlW0Pt6wW8f3N2aYfMX9CG0
            E4/izo+btWYTHF8LgNDsP/KQ2xu6yV2ZNjN/lISJAOiprusCvCtRPQEWQiF8k3XS
            XgGKuflplkHHlb+jeKIr+sbUiIg4QAyngMn1ZqiNP0ixyEEcvQRDJsiveurasGOB
            o+goKGZIlvmZWA1Sop0Uv4rJWI6PjOQvzDDEN1eKfXk0/sDWGyJjZ/l9BzXWFZk=
            =CI7i
            -----END PGP MESSAGE-----
          fp: 73880ECAF69EC2ED44CE5889502BFB12D0B5295F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
