samba_username: ENC[AES256_GCM,data:0LD2kJ/jfW/Mm3Wg,iv:m2ioNKOLeDo8EBRthHi6CQtSVa9ueC8bmilKC2UymUo=,tag:l2iVzcOvpiRUCS1NwEWbYw==,type:str]
samba_password: ENC[AES256_GCM,data:iXnhFmyYTJKOEJNR,iv:ur7o6TPEIbELx1+F6insMUDp7by+8Laz9zni6rqjO6U=,tag:EWTsnT+EEURCqfFP3y0K1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15qauah7skmftfg5u4z4l526uas5gqaze6k6d09fm7jnga0zzuqtsfy3m5n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTjYwVWR6YWRHRUM1WU5S
            Ukt5TWdGYXowQ1Y3RktMaHo3NWxhb0x5elZ3CmovRG4xbHREQ1FYbXpyQUlMczNS
            NHJBd2xLNXZsMnkrRXRqQ1ZnbGp6bmsKLS0tIEhYbVZOMjcyaU0rbkJ0eGhnc2Yr
            WldJaENiMUQzQWo2VWQ4K0xmWlZGVEUKzxUaW49+ck/FCw0ADpJ7EgtL/fwV9yim
            lzt6BKHfQoKXQPemUzf9mnTE1iiQxhkyUDuaFnqSk58K45MQxFfgfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yq5m2qs0ghd87wclpg9vcntql9sxfex06xs6d4efk6n2d80mkp9qrk70yv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dlIwZ2pxNE55NHpiK082
            ZXc1QjNiZGJ1a3lPZGZxVWVwWEdNeW0wWkNNCk5yU1FKbmZBQjBDQWR1UFNBc2hp
            M0NkT1V6V1lTc1BhMVJVSlhZdWc5V0EKLS0tIFUxVFgzU1ZxaXFjUUFjWlA2WEhv
            WkR1elMxS2YwZVZPQm5wOUdvU05CUFkK1M8+p0QqIDqefoQzuYL8YRNmoaqhoOLr
            HUFge3/nS3lhODJ/yupJgzZOf2NyY/h69AHpOrsnJBp0+twN3PYsdA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12j6e5yspv9yw7cprqegfprqg39vde3qxkfggscksrneu0pkwju3se80x7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucHhNVjdzTFZQekQ3Z29W
            ekw0YUhmU2t5Mkt1OVBGTHNHTFBjTWxScFcwCitvNEkzY0hyUGlRQjRVeWU0bWxx
            S2kyY3VHOHpaaGI5MkRqRHY1Tm53MjQKLS0tIFQwbW1zaTF5RHgyYXU0d2FZdnI1
            VytCYzZoWmxrKzJnbzZhQ3AzVUZrMUkKUZey0cBTGhIB5udBaL14TmYoZitMhSFV
            m/wqt3pRKPA8qbKaq9HMhQ+gF1Gn7n1rRwpiA9vu2ePIaP2Y41QOug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f9uy7mcfdm7skndsa9p5zu9xqfs8hahxtzg75e4vktrkvqc9qu5q89fdzf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZjUrYTV6Rk11OU1zdlpR
            d3U5MjdTV1FFVThsb2RuY2xDcExjeWpMZ2s4Cm9Tb3l4YmtZNi9ScFNFU0htY0JJ
            R3ZobkJkaE9UV2NkeW1ReEl2eWxlUWcKLS0tIDN6OFllUXZEZXl3ZGFRdVZ0dVdS
            UWtVRVh2aTJqL1QxN2ZEOXo0RmQveWsKgvoT07Lnrjng/roaWNjllPy6XPXr2D7P
            k1XQYLVRWm6b2jvTYM3wNTx+PPnOZk8eWfOwLmu630nSUN6oPIRfqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T15:42:41Z"
    mac: ENC[AES256_GCM,data:vethvGwwpGwkw80GGZLlvBLyDcEqsCMXTnyLnGzBbmoMqBSgAohjjvHGv85Ls9pGa7ghne1wT9cF6AlVgrD8P/Hg8j/2mbzpiVd9Jz3Vms8oK8zBaSiR2FThZZCKK90JpigVecKUCvbZduIER4EdmuTJiEe2QoFH0eHvFbxBbSU=,iv:CmaG0MAW196ZQMzOO3YE2soH0k/Llb7bmmTfGUpDk1g=,tag:MiEsBelo/W3dbTl9ghcEiw==,type:str]
    pgp:
        - created_at: "2024-06-09T18:43:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwEkGKbmunUuAQ/9EubWxIvAEyPX1cmCUz5s6OnRmokRl/ehTqDxD0nsPzoO
            7WHEVXSWSpHWWzbWYr/qeyk/d3uGBKPwdjXRdm7Xdk1DFtA/Xlq3vHw1gLdV7xzm
            jVKHvGAxLULzfRQx+HXjDxK4XnHV7sCnTaklH1sijEvaQnK/7+0h/Vi7mDMbJNNK
            JuSBuTalc6rTU13MaeckQ6vSMLDBvHVPu8eQS3ZqobkMwB494FHDwjc+2jCg1lFX
            0uJXPUYs27v6TWAfUUwA1ujayvaA6c/I+A03TWb5vL9/yDoEWRMi0qncsC0681iZ
            69lFeHxJmi86v2oCEl+vU2ydPzz30JKqdQ5CdqzJl+47+leIfqsoZbwy0ARr12mj
            VArq4/LFF8YQAMjQSYnCO5C3mLIRJlyBSoK+2iGE/33MLIxJobjFQ8TZZdhsGSw1
            7zJ8RZQTbkVnxvDiOMu0NWBE1lIs0igFQrAxRayCTWCUA9XfM3NltxBQUU0c6aC/
            JLGV3/QvLH+qyJAtQI+nc8G8uXZE753CqAXW7WxN1CWx5z3Bdr5gqwW62dk5ZJKj
            RpHpHgMWBPax4z5RNo9GWdistqytoVSNwBI9bN+1s44s6b4cTlX3yyUikji0mh7Y
            TuWVfuwRB3hwvJnv5ftqj/LkIjCKXQvr7SXeGIUES1O7lKMyU26r+8a8htnd+8rS
            XgGWxUpHETkDcFtFQNRupRbHaHy4z1z5dNGdDk+QKDiLZEq+5CK6pnUK/WWbtfY1
            N3R08GDwWS4R7uIL58XS1yx2hBuNyHRLC2InXnj/+XPbFeBttwTU/KDcAY1keFg=
            =Gspn
            -----END PGP MESSAGE-----
          fp: 73880ECAF69EC2ED44CE5889502BFB12D0B5295F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
