---
- name: Setup samba users
  hosts: storage
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Load encrypted credentials
      community.sops.load_vars:
        file: samba.sops.yaml

    - shell: |
        echo "{{ samba_password }}\n{{ samba_password }}\n" | smbpasswd -sa {{ samba_username }}

    - file:
        path: /etc/samba/smbusers
        state: touch
        owner: root
        group: root
        mode: 0644
